### ISSUE TITLE
https://searsh.me/

### ISSUE THREAD

**Issue by Kiznaiver-system** [searxng/searx-instances#10]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed antibot-proxy or another bot protection.

### Comment

Hello this is my searx instance called searsh.
the instance is also accessible via tor

**Comment by Kiznaiver-system** [comment]
*the tor link is http://zele4fqv57ncb6ogo2au7ye6viwzarkvxckajl6eeq65c37qz4dfuiid.onion/

**Comment by unixfox** [comment]
Hello,

Your instance seems to be broken, I get a timeout error when searching on it.

**Comment by unixfox** [comment]
Closing as your site doesn't respond anymore.
