### ISSUE TITLE
Add https://searx.fi

### ISSUE THREAD

**Issue by RoyTakanen** [searxng/searx-instances#103]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by ononoki1** [comment]
Hi @RoyTakanen 

There are some issues with your instance.

- Your [CSP](https://observatory.mozilla.org/analyze/searx.fi) config is not optimal. It's recommended to optimize it to better protect user's security.
- You did not configure the limiter plugin well. I can still make search requests via curl: `curl https://searx.fi/search?q=test`.

Your instance can still be added in searx.space even if you do not fix the issues above. It will just be ranked lower or more vulnerable to robots. Please confirm whether you wish that your instance would be added anyway or fix those issues accordingly.

**Comment by RoyTakanen** [comment]
Hi @ononoki1,

Thanks for the reply. I will configure the limiter plugin and fix CSP config before addition. I will send a message here after I am done.

**Comment by dalf** [comment]
Hi @RoyTakanen 
Is there any reason to use the version `2022.03.13-cd92a7ea` rather than the last one?

**Comment by RoyTakanen** [comment]
Hi @dalf! The reason for that is that I did not remember to update my instance 😁. I will set up watchtower to pull the latest version automatically.

**Comment by RoyTakanen** [comment]
Hi @ononoki1,

I think that the limiter works now (I do not get any results when using curl). I also improved the score on Mozilla Observatory: https://observatory.mozilla.org/analyze/searx.fi. Is there something else I should be aware about?

**Comment by tiekoetter** [comment]
@RoyTakanen Your CSP header prevents the JS from being executed. Maybe relax it a bit.

Your [TLS](https://cryptcheck.fr/https/searx.fi) grade is also not really good (Do you use a custom cipher list?)

**Comment by RoyTakanen** [comment]
@tiekoetter thank you for your response. I copied the CSP from [here](https://github.com/searx/searx-docker/blob/master/Caddyfile#L82). Now I have switched to use the one on line 86.

I am using traefik as my web server and I do not use custom cipher list. I can try to change my configuration to support more ciphers.

**Comment by tiekoetter** [comment]
@RoyTakanen The problem is not to support more ciphers; You need to support fewer ciphers. This might help you: https://github.com/searxng/searx-instances/issues/62#issuecomment-1126793414

You should also consider enabling the image proxy by default (https://github.com/searxng/searxng/blob/5672f5ad2a535b25b38cc73ad4d00e71c0d443c9/searx/settings.yml#L58).

**Comment by ononoki1** [comment]
@RoyTakanen I cannot open your site now. Do you still want to add your instance to public list?

**Comment by RoyTakanen** [comment]
@ononoki1 I was having problems while I tried to limit supported ciphers. Is it okay to add the to the list even though it does not restrict ciphers? If so I would like it to be added.

**Comment by return42** [comment]
> I was having problems while I tried to limit supported ciphers.

May https://github.com/searxng/searxng/discussions/1351 gives you a starting point.

**Comment by unixfox** [comment]
Your instance is already at 50% of uptime for 5 days which is very low.

Make sure to watch out for the availability of your instance or we will have to remove it from the list. If you have issues with your server we recommend asking to remove it until you fix these.

**Comment by RoyTakanen** [comment]
Hi @unixfox. Thanks for the message. I actually noticed the poor uptime earlier today. I think that I fixed it with a little change to my config. I will see how well it does for the next few days. In case the service does not keep up I will ask it to be removed.
