### ISSUE TITLE
Add https://notgoogle.win

### ISSUE THREAD

**Issue by owengaspard** [searxng/searx-instances#104]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

N/A

**Comment by unixfox** [comment]
Instance removed due to bad uptime: https://github.com/searxng/searx-instances-uptime/issues/294
