### ISSUE TITLE
Add https://searx.slipfox.xyz/searx

### ISSUE THREAD

**Issue by Slips-PC** [searxng/searx-instances#106]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

An onion service is also provided at http://fub6vgedgeadlu3ctskrpkcqjruh76tckwtj5swfhyblgml2tzgzckqd.onion/searx/

**Comment by tiekoetter** [comment]
Hi @Slips-PC

Your [CSP](https://observatory.mozilla.org/analyze/searx.slipfox.xyz) and [TLS](https://cryptcheck.fr/https/searx.slipfox.xyz) grade are not optimal.
The morty result proxy doesn't work on your instance (I would recommend switching to the [integrated image proxy](https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings.yml#L66) if you don't need to proxy web pages).
Filtron also doesn't work on your instance (`curl -i "https://searx.slipfox.xyz/searx/search?q=test"` is returning results instead of error 429)

Your instance can be added anyways if you wish but keep in mind that your instance will be ranked lower, may be flooded by bots and/or has broken features.

**Comment by Slips-PC** [comment]
> Your [CSP](https://observatory.mozilla.org/analyze/searx.slipfox.xyz) and [TLS](https://cryptcheck.fr/https/searx.slipfox.xyz) grade are not optimal.

Noted. What would be a good CSP for something like searxng?

> (I would recommend switching to the [integrated image proxy](https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings.yml#L66) if you don't need to proxy web pages).

Alright, will enable that.

As for switching to the integrated limiter, i'll enable that, but how can I test to make sure that's working?

Hold off on adding it for now while I fix some of these issues.

**Comment by tiekoetter** [comment]
@Slips-PC 
For the CSP header you could use something like what I mentioned in this comment https://github.com/searxng/searx-instances/issues/45#issuecomment-1100486633. You should also set the following headers: `X-Frame-Options` and `Strict-Transport-Security`

You can check if the limiter plugin is working by running the curl command `curl -i "https://searx.slipfox.xyz/searx/search?q=test"`, if it returns error 429 it is working if it returns anything else it is not.

**Comment by Slips-PC** [comment]
@tiekoetter 
Got it.
So I've got the CSP issue solved (turns out the CSP i use for most of my other sites works fine for SearXNG as well), but how do I solve the TLS problem?

**Comment by tiekoetter** [comment]
@Slips-PC 
You would need to use a custom cipher list
Example cipher list: `ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305`

Your current CSP header breaks some things (like embedded videos) you should probably adjust this (Your can check the browser console for errors regarding the CSP header). Your instance has a duplicate `x-content-type-options` header.

**Comment by Slips-PC** [comment]
@tiekoetter 
Alright, so I copied your CSP from the listed issue post, I copied your cipher list so I *think* I got TLS right (but I couldn't check it since the site you linked has a 24 hour refresh), got the image proxy working (I think) and also got the rate limiter working. I think that's everything?

**Comment by tiekoetter** [comment]
@Slips-PC You should probably replace the link of my SearXNG fork and Invidious instance from your CSP header.

**Comment by Slips-PC** [comment]
Ah, whoops. Guess I missed that. I'll handle that when I get back to my PC in a couple hours.

Does this issue getting closed mean my instance is getting added to the list?
