### ISSUE TITLE
Add https://search.comradeturtle.dev

### ISSUE THREAD

**Issue by ComradeTurtle** [searxng/searx-instances#107]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

Additional bot protection is in place by litespeed & cloudflare.

SSL score is A:
https://www.ssllabs.com/ssltest/analyze.html?d=search.comradeturtle.dev&hideResults=on

**Comment by tiekoetter** [comment]
I haven't checked your instance yet but we strongly recommend not using Cloudflare because they MITM every request by design.

**Comment by ComradeTurtle** [comment]
Understandable. I put cloudflare in between in order to protect my server but I can disable proxying if it is such a big problem.

**Comment by unixfox** [comment]
> Understandable. I put cloudflare in between in order to protect my server but I can disable proxying if it is such a big problem. 

If you want to protect your server we recommend using a more specialized software made for searxng.

Like the limiter plugin: https://docs.searxng.org/src/searx.plugins.limiter.html#limiter-plugin

**Comment by ComradeTurtle** [comment]
Fair enough. I'll be disabling cloudflare proxying then

**Comment by ononoki1** [comment]
Hi @ComradeTurtle 

Your [CSP](https://observatory.mozilla.org/analyze/search.comradeturtle.dev) grade is not optimal. It's recommended to improve it to better protect user's security.

Your instance can still be added in searx.space even if you do not follow the advice above. It will just be ranked lower. Please confirm whether you wish that your instance would be added anyway or change your config accordingly.

**Comment by ononoki1** [comment]
@ComradeTurtle Any update?

**Comment by ComradeTurtle** [comment]
I guess I need some help configuring CSP because I have not figured out how to improve it. I'm using LiteSpeed for my web server. Any ideas?

**Comment by ononoki1** [comment]
This is an example: https://github.com/searxng/searxng-docker/blob/b1b174a3392275f0c9d323c82ec9d45055ac124a/Caddyfile#L85

**Comment by ComradeTurtle** [comment]
But where do I apply these settings? I don't seem to be able to find anything related to CSP in LiteSpeed.

**Comment by ComradeTurtle** [comment]
I have been battling with LiteSpeed for the last couple of hours and I can't seem to get the extra header to show up. I've tried putting it in the rewrite rules and I've tried creating a context with no luck:(

**Comment by return42** [comment]
> But where do I apply these settings?
> I have been battling with LiteSpeed ..

Why are you not using the `/etc/searxng/settings.yml` like shown in the link from mine above?

**Comment by ononoki1** [comment]
> Your instance can still be added in searx.space even if you do not follow the advice above. It will just be ranked lower. Please confirm whether you wish that your instance would be added anyway or change your config accordingly.

@ComradeTurtle As said here, your instance can still be added even with imperfect CSP grade. You can modify your CSP header later but add your instance now. Would you like to do that?

**Comment by ononoki1** [comment]
@ComradeTurtle Any update?

**Comment by ononoki1** [comment]
Close due to lack of reply.
