### ISSUE TITLE
Add https://doh.syncpundit.com/searx

### ISSUE THREAD

**Issue by Deon-Trevor** [searxng/searx-instances#11]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by unixfox** [comment]
Hello,
Could you serve searx from the root domain (/) instead of /searx?

**Comment by Deon-Trevor** [comment]
> Hello, Could you serve searx from the root domain (/) instead of /searx?

I will setup a dedicated subdomain for searx in the near future, for now it's sharing the server with something else that'll be using the root dir

**Comment by unixfox** [comment]
I know it's not really listed as a requirement, but I would prefer if searx is served from the root path directly.

We don't have any public instance that don't serve from the root path and as a user I would prefer to have the shorter URL as possible.

**Comment by Deon-Trevor** [comment]
Got ya. Thanks, let me work on that. I'll open another issue when i'm done

**Comment by unixfox** [comment]
No need to open another issue. Just edit the current one, even just the title of the issue.

**Comment by Deon-Trevor** [comment]
Will do. Thanks

**Comment by unixfox** [comment]
You can reopen this issue once you have done this change.
