### ISSUE TITLE
Add https://search.unlocked.link

### ISSUE THREAD

**Issue by kerkmann** [searxng/searx-instances#111]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by kerkmann** [comment]
Is it just recommended to disable Cloudflare?
Otherwise, I would let it enabled. :)

**Comment by unixfox** [comment]
It is indeed not recommended to enable cloudflare. See https://github.com/searxng/searx-instances/issues/107#issuecomment-1173008221

**Comment by kerkmann** [comment]
Okay, I'll remove Cloudflare, give me a sec. :)

**Comment by kerkmann** [comment]
Okay, fixed it, it's now using Lets Encrypt and SSL Labs says A+

https://www.ssllabs.com/ssltest/analyze.html?d=search.unlocked.link&latest

**Comment by kerkmann** [comment]
Also added IPv6 support. :)

**Comment by ononoki1** [comment]
Hi @kerkmann 

Your [CSP](https://observatory.mozilla.org/analyze/search.unlocked.link) grade is not optimal. It's recommended to improve it to better protect user's security.

Your instance can still be added in searx.space even if you do not follow the advice above. It will just be ranked lower. Please confirm whether you wish that your instance would be added anyway or change your config accordingly.

**Comment by kerkmann** [comment]
> Your [CSP](https://observatory.mozilla.org/analyze/search.unlocked.link) grade is not optimal. It's recommended to improve it to better protect user's security.

Thanks for mention it! Never knew that this exists. :)
Fixed it yet. :3

**Comment by ononoki1** [comment]
Your CSP policy is too strict that image search works poorly (e.g. https://search.unlocked.link/search?q=test&category_images=on). You may need to change `img-src 'self'` to `img-src 'self' data:`.

**Comment by kerkmann** [comment]
Thanks @ononoki1 , you're totally right. I weakened it. :)
