### ISSUE TITLE
Edit https://opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searx-instances#114]
Instance added by the issue 87

Hello, I apologize for not keeping the uptime. This was due to a haproxy issue, which I have fixed. Would you consider reinstating my instance? Thank you.

**Comment by unixfox** [comment]
If you know that your server has some issue then please ask to remove it.

We can add it back but if next time you have again some uptime issue and we have to discover it by ourselves then we won't add it back a second time to the public list.
