### ISSUE TITLE
Add https://searx.vanwa.tech

### ISSUE THREAD

**Issue by NickTheLim** [searxng/searx-instances#115]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have installed another bot protection.

### Comment

We operate the ISP hosting the service, as well as the CDN

Bot protection is done via our Javascript validation

**Comment by ononoki1** [comment]
Hi @NickTheLim 

Your [TLS](https://cryptcheck.fr/https/searx.vanwa.tech) and [CSP](https://observatory.mozilla.org/analyze/searx.vanwa.tech) grades are not optimal. It's recommended to improve them to better protect user's security.

Your instance can still be added in searx.space even if you do not follow the advice above. It will just be ranked lower. Please confirm whether you wish that your instance would be added anyway or change your config accordingly.

**Comment by NickTheLim** [comment]
Hi @ononoki1 thank you for the quick response - we would like the instance to still be added to the list. We plan to roll out an update soon to increase the TLS grade as well. 

Additionally, we have also exposed this service on the deep web: http://searx.vanwa.tech.4o5xwl3fsmzwys7edqxtohvva6ikxc6h7wt7el4ar3d5om6k2zz7yaqd.onion/

**Comment by unixfox** [comment]
> Bot protection is done via our Javascript validation

What happens if someone doesn't activate javascript? Does your instance block them?

**Comment by NickTheLim** [comment]
I have disabled the Javascript validation

**Comment by tiekoetter** [comment]
@NickTheLim Your instance is currently down. (https://github.com/searxng/searx-instances-uptime/issues/286)

Please keep in mind that we will remove the instance if the uptime drops below 90% / 30 days.

**Comment by tiekoetter** [comment]
@NickTheLim It is down again (https://github.com/searxng/searx-instances-uptime/issues/339).

**Comment by NickTheLim** [comment]
Back up, sorry about that, took a while for the government to release the censorship

**Comment by unixfox** [comment]
Not sure what you are talking about the censorship... But your instance has now an uptime of 81% which is well below the required uptime of 90%.

It was down 7 hours too for 1 hour: https://github.com/searxng/searx-instances-uptime/issues/349

We can't keep instances that are down for too much time. If we find that your instance is down again, we will have to remove it until you fix the issues on your side that makes your instance unstable.

**Comment by unixfox** [comment]
Hello your instance is very unstable, a lot of downtimes: https://github.com/searxng/searx-instances-uptime/issues?q=is%3Aissue+sort%3Aupdated-desc+searx.vanwa.tech+is%3Aclosed

It has an uptime below the required 90%, but we can do an exception if you tell us what's happening. But if we find out that your instance is down again, we will have to remove it from the public list.

**Comment by NickTheLim** [comment]
We just rolled out a bunch of updates to our networks that will significantly increase resiliency.

Our networks were being dropped from the routing tables.

We will continue to innovate further and I have also enhanced my monitoring as well.
