### ISSUE TITLE
Add https://icanfindit.online

### ISSUE THREAD

**Issue by rattfieldnz** [searxng/searx-instances#118]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by unixfox** [comment]
Hello, your instance has been down for 2 days and has an uptime below 90% which is under the required uptime for the public instances.

Please notify us about any downtime for your instance here: https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime

We can add back your instance, but if we found out by ourselves again that your instance is below the required uptime, it will be permanently removed.
