### ISSUE TITLE
Add https://search.gcomm.ch

### ISSUE THREAD

**Issue by dguazzon** [searxng/searx-instances#119]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have installed another bot protection.

**Comment by ononoki1** [comment]
Hi @dguazzon 

There are some issues with your instance.

1. **You may not configure NGINX's reverse proxy well. Normal search requests are rate-limited (e.g. https://search.gcomm.ch/search?q=test).**
2. Your [CSP](https://observatory.mozilla.org/analyze/search.gcomm.ch) grade is not optimal. It's recommended to improve it to better protect user's security.
3. Your web server only supports HTTP/1.1. We recommend you to enable HTTP/2 to improve performance. I noticed that you are using NGINX. You can simply [add http2 parameter in `listen` directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen).
4. It seems that both root path `/` and path `/searx/` are available for searching (i.e. https://search.gcomm.ch/search?q=test and https://search.gcomm.ch/searx/search?q=test). Is that intentional?

Please at least fix the first issue to let users use your instance normally. Other issues can be ignored if you don't mind your instance being ranked lower in searx.space.

**Comment by dguazzon** [comment]
Hi

The instance is behind an HAproxy and the settings were not optimal. 
CSP and http/2 are now enabled. 
Limiting is now on the HAproxy and not anymore using the embedded limiter. 
The search path is on purpose like this. 

Best regards

Daniele Guazzoni

Email: ***@***.***

> On 12 Jul 2022, at 09:37, ononoki ***@***.***> wrote:
> 
> ﻿
> Hi @dguazzon
> 
> There are some issues with your instance.
> 
> You may not configure NGINX's reverse proxy well. Normal search requests are rate-limited (e.g. https://search.gcomm.ch/search?q=test).
> Your CSP grade is not optimal. It's recommended to improve it to better protect user's security.
> Your web server only supports HTTP/1.1. We recommend you to enable HTTP/2 to improve performance. I noticed that you are using NGINX. You can simply add http2 parameter in listen directive.
> It seems that both root path / and path /searx/ are available for searching (i.e. https://search.gcomm.ch/search?q=test and https://search.gcomm.ch/searx/search?q=test). Is that intentional?
> Please at least fix the first issue to let users use your instance normally. Other issues can be ignored if you don't mind your instance being ranked lower in searx.space.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


--
This e-mail and any attached files are confidential and may be legally privileged. If you are not the addressee, any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication is strictly prohibited. If you have received this transmission in error please notify the sender immediately and then delete this mail.
E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission or changes to transmitted date not specifically approved by the sender.
If this e-mail or attached files contain information which do not relate to our professional activity we do not accept liability for such information.

**Comment by ononoki1** [comment]
Your instance is unavailable (503 Service Unavailable) now. Please note that we have minimum 90% uptime requirement. Your instance will be added as soon as your instance returns normal.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.
