### ISSUE TITLE
Add https://search.projectsegfau.lt

### ISSUE THREAD

**Issue by openssl-rand** [searxng/searx-instances#121]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by tiekoetter** [comment]
Hi @openssl-rand
The [TLS](https://cryptcheck.fr/https/search.projectsegfau.lt) and [CSP](https://observatory.mozilla.org/analyze/search.projectsegfau.lt) grade are not optimal.
The limiter plugin is not working on your instance. Running `curl -i "https://search.projectsegfau.lt/search?q=test"` returns results instead of error 429. Check your limiter and redis config.
Searching for `ip` (https://search.projectsegfau.lt/search?q=ip) returns an internal IP address. You should check which headers nginx passes to SearXNG.

**Comment by openssl-rand** [comment]
Hello, thanks for reaching out. Do you know how to configure nginx to use stronger ciphers? The rest of the issues I think i can figure out.

**Comment by tiekoetter** [comment]
@openssl-rand You need to enable `ssl_prefer_server_ciphers` in your server block for SearXNG and set the cipher list to something like this `ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;`

Reference: http://nginx.org/en/docs/http/ngx_http_ssl_module.html

**Comment by openssl-rand** [comment]
set that up at the global level at /etc/nginx/nginx.conf. waiting for refresh
also where does the services.limiter go into the config file. like under which category like `global` `search`

**Comment by openssl-rand** [comment]
Mozilla returns A+ in the observatory after I added all the headers.

**Comment by tiekoetter** [comment]
You should look into enabling the image proxy by default. You should also relax your CSP header a bit more as it currently breaks embedded videos for example.

**Comment by openssl-rand** [comment]
I have no idea how CSP works and when I look it up online it is very hard to understand.

**Comment by tiekoetter** [comment]
@openssl-rand You can either look at instances like searx.be, paulgo.io or search.ononoki.org or use something like what I have posted here https://github.com/searxng/searx-instances/issues/45#issuecomment-1100486633 for your CSP header.

The limiter setting goes under `server:`

**Comment by openssl-rand** [comment]
CSP is setup, limiter is enabled but doeesn't work. Redis url should be correct

**Comment by tiekoetter** [comment]
@openssl-rand Could you provide a debug log?

If you use the unix socket for redis check the permissions and path.

**Comment by openssl-rand** [comment]
[_searxng_logs.txt](https://github.com/searxng/searx-instances/files/9105197/_searxng_logs.txt)
Important lines are 
```
2022-07-13 19:06:17,600 ERROR:searx.shared.redis:   Error 99 connecting to localhost:6379. Address not available.
2022-07-13 19:08:59,363 ERROR:searx.shared.redis:   Error 111 connecting to 127.0.0.1:6379. Connection refused.
2022-07-13 19:08:59,363 ERROR:searx.plugins.limiter: init limiter DB failed!!!
2022-07-13 19:08:59,408 ERROR:searx.shared.redis: can't connet redis DB ...
```

It is running inside a docker container, that probably could affect the network connectivity because I can run `redis-cli` and it works.

**Comment by openssl-rand** [comment]
Changed to socket instead of network, and now it works. Using `curl` on a /search route returns 429.

**Comment by tiekoetter** [comment]
@openssl-rand I now get instantly rate-limited.

**Comment by openssl-rand** [comment]
Is there a config option I need to change like "requests-per-second" or something? Or should limiter be working out of the box.

**Comment by tiekoetter** [comment]
@openssl-rand It should be working out of the box.

Check if every header mentioned in the install guide is passed correctly to SearXNG. https://docs.searxng.org/admin/installation-nginx.html

**Comment by openssl-rand** [comment]
Yeah I wasn't passing the headers correctly, now appears to work

**Comment by openssl-rand** [comment]
Well it already supports TLSv1.3 and all that stuff, and I am using the ciphers that you recommended, so I think you can just add it.

**Comment by openssl-rand** [comment]
Thanks for helping me setup this instance, first time making searx instance that is actually publicly useable. Its nice to see that there are strict requirements for getting an instance on the listings. Thank you and have a great day!

**Comment by tiekoetter** [comment]
@openssl-rand I don't think you setup the ciphers correctly because the instance still has an "E" grade. https://cryptcheck.fr/https/search.projectsegfau.lt

**Comment by openssl-rand** [comment]
Just add the instance for now, il fix ciphers later

**Comment by openssl-rand** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=search.projectsegfau.lt&hideResults=on

SSL Labs reports A+

**Comment by openssl-rand** [comment]
Thanks!
