### ISSUE TITLE
Add https://private-searx.ml

### ISSUE THREAD

**Issue by HunterMcClurg** [searxng/searx-instances#122]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by tiekoetter** [comment]
@HunterMcClurg IPv4 is broken on your instance. Please fix this.

**Comment by HunterMcClurg** [comment]
@tiekoetter Hello, I believe the issue should be resolved now.

**Comment by HunterMcClurg** [comment]
Actually, I think I addressed the wrong issue. When I did `ping private-searx.ml` I wasn't getting a response and realized I needed to allow echo requests over ICMP for IPV4 and IPV6. You probably meant the IPV4 error on https://cryptcheck.fr/https/private-searx.ml -- I will follow up when this is resolved.
