### ISSUE TITLE
Add https://searx.delicta.pp.ua

### ISSUE THREAD

**Issue by DziubaMaksym** [searxng/searx-instances#123]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have installed another bot protection.

**Comment by ononoki1** [comment]
Hi @DziubaMaksym 

Your instance is using Cloudflare as reverse proxy, which is forbidden unless you have proper reasons. Please either disable Cloudflare or give proper reasons for using Cloudflare.

**Comment by DziubaMaksym** [comment]
Hi @ononoki1, I'm using Cloudflare for DDoS protection and bot protection and also for the cache.
If it's not a good reason why I use it, feel free to close the issue. Have a great day!

**Comment by ononoki1** [comment]
You can use SearXNG's internal [limiter plugin](https://docs.searxng.org/src/searx.plugins.limiter.html) for bot protection. And you can enable [static_use_hash](https://github.com/searxng/searxng/blob/7bf4e8d12d1d0ee53bf71f7c3a4010ef936f25d9/searx/settings.yml#L86) and use headers like `Cache-Control: max-age=31536000, immutable` for static assets  cache.

What do you think?

**Comment by DziubaMaksym** [comment]
> You can use SearXNG's internal [limiter plugin](https://docs.searxng.org/src/searx.plugins.limiter.html) for bot protection. And you can enable [static_use_hash](https://github.com/searxng/searxng/blob/7bf4e8d12d1d0ee53bf71f7c3a4010ef936f25d9/searx/settings.yml#L86) and use headers like `Cache-Control: max-age=31536000, immutable` for static assets  cache.
> 
> 
> 
> What do you think?

Looks great, but I think that I would need some time to implement and test all of this. Feel free to close this issue, and I'll open a new one when everything is ready.
