### ISSUE TITLE
Edit https://icanfindit.online

### ISSUE THREAD

**Issue by rattfieldnz** [searxng/searx-instances#125]
Due to my AWS instance becoming corrupted,  my searx instance will be offline for a few hours. I am currently creating a new AWS instance and will install SearXNG on there. Will let you know once I have got my instance back online.

Apologies if this is the wrong place for such a 'change'.

**Comment by rattfieldnz** [comment]
Have got the instance fully running again. Amazed that AWS DNS changes work so quickly.

**Comment by unixfox** [comment]
Thank you for notifying us about that, I guess we should do a new type of instance for planned downtimes.

**Comment by rattfieldnz** [comment]
> Thank you for notifying us about that, I guess we should do a new type of issue for planned downtimes.

Not a problem. I want to maintain as close to 100% uptime as possible. If a lot of traffic comes to my instance and my AWS free tier can't handle it, I'd have to look at ways to monetize it. But I do see the importance of a privacy-respecting metasearch engine.

Yes, the new type of issue would be a great idea. How would that be implemented in the auto checking scripts?

A micellaneous question: Why are instances deployed on AWS highlighted in red, as in my attached screenshot?
![Screenshot 2022-07-15 222319](https://user-images.githubusercontent.com/2468863/179205150-c2c3ac68-0b5b-4106-ada3-84356c1ff843.png)

**Comment by unixfox** [comment]
> > Thank you for notifying us about that, I guess we should do a new type of issue for planned downtimes.
> 
> Not a problem. I want to maintain as close to 100% uptime as possible. If a lot of traffic comes to my instance and my AWS free tier can't handle it, I'd have to look at ways to monetize it. But I do see the importance of a privacy-respecting metasearch engine.
> 
> Yes, the new type of issue would be a great idea. How would that be implemented in the auto checking scripts?
> 
> A micellaneous question: Why are instances deployed on AWS highlighted in red, as in my attached screenshot?
> ![Screenshot 2022-07-15 222319](https://user-images.githubusercontent.com/2468863/179205150-c2c3ac68-0b5b-4106-ada3-84356c1ff843.png)
> 

Can you create a github discussion for discussing about that?
