### ISSUE TITLE
Edit search.chemicals-in-the-water.eu

### ISSUE THREAD

**Issue by somerandomusername666** [searxng/searx-instances#126]
Instance added by the issue #72 

Also available at search.citw.cc

**Comment by unixfox** [comment]
If it's the same instance I don't think we add a duplicate domain, we keep one of the two domains not both.

**Comment by somerandomusername666** [comment]
Hello,

The one at search.citw.cc is basically on another server incase the server the .eu domain uses goes down for whatever reason.

**Comment by unixfox** [comment]
Can't you just serve `search.chemicals-in-the-water.eu` from your two servers? You can add multiple IP addresses with two different A records.

**Comment by somerandomusername666** [comment]
I honestly haven't thought about doing that at first, so thats definitely a good plan

**Comment by unixfox** [comment]
Can I close the issue if you are satisfied with my solution?

**Comment by somerandomusername666** [comment]
Sure, thats fine with me

**Comment by somerandomusername666** [comment]
Same instance as in both on same server or?
The other domain is on a different server
