### ISSUE TITLE
Add https://nogoogle.nl

### ISSUE THREAD

**Issue by hpowernl** [searxng/searx-instances#127]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by ononoki1** [comment]
Hi @hpowernl 

Your [CSP](https://observatory.mozilla.org/analyze/nogoogle.nl) grade is not optimal. You can add proper `Content-Security-Policy` header to improve it. An example is [here](https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L85).

Your instance can be added even if the issue above is not fixed. It will just make your instance rank lower on [searx.space](https://searx.space). Please confirm whether you want to fix your CSP first or just add your instance now.

**Comment by ononoki1** [comment]
@hpowernl Any update?

**Comment by hpowernl** [comment]
Not yet, this requires a platform adjustment.
