### ISSUE TITLE
Add https://futursearch.gq

### ISSUE THREAD

**Issue by hxvy0** [searxng/searx-instances#129]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

please add

**Comment by ononoki1** [comment]
Your instance is using Cloudflare as reverse proxy, which is not recommended due to privacy issue. Please either disable Cloudflare or give proper reasons for using it.

**Comment by hxvy0** [comment]
Okey. Are u added?

**Comment by unixfox** [comment]
> Okey. Are u added?

You probably didn't understood the question.

Please disable cloudflare proxy (orange icon on their panel) OR give good reasons why you want to keep cloudflare.

**Comment by ononoki1** [comment]
@hxvy0 Any update?

**Comment by hxvy0** [comment]
Bruh

**Comment by hxvy0** [comment]
My PC was broken. That's why I couldn't write.

**Comment by ononoki1** [comment]
> Your instance is using Cloudflare as reverse proxy, which is not recommended due to privacy issue.
>
> Please either disable Cloudflare or give proper reasons for using it, otherwise your instance will not be added.

**Comment by hxvy0** [comment]
Don't put it on. Because I have to use cloudflare.

**Comment by ononoki1** [comment]
> Don't put it on. Because I have to use cloudflare.

Cloudflare is acceptable as long as you told us the proper reason for using it.

**Comment by hxvy0** [comment]
> Cloudflare is acceptable as long as you told us the proper reason for using it. 

 The site is getting much faster. There is a difference of 45 seconds.

**Comment by hxvy0** [comment]
> > The site is getting much faster. There is a difference of 4, 5 seconds.
> 
> IMO this is not a good reason. If your instance is slow, you should upgrade your server's hardware or change its location.

Will u add or not? My servers speed so good with cloudflare

**Comment by ononoki1** [comment]
> Will u add or not?

No.

**Comment by hxvy0** [comment]
why

**Comment by ononoki1** [comment]
> why

I think I've said enough about it. There is explicit instruction in `Recommendations for your instance` of [add-instance issue template](https://github.com/searxng/searx-instances/blob/master/.github/ISSUE_TEMPLATE/add-instance.yaml), which says:

> Try to not use Cloudflare or any other commercial solution that analyze the HTTP traffic between the user and the server.
It's bad for the privacy because the provider can see all the HTTP traffic between the users and your server.
Prefer using [the built-in limiter plugin](https://docs.searxng.org/src/searx.plugins.limiter.html#limiter-plugin) for SearxNG or [filtron](https://github.com/searxng/filtron) for SearX.

**Comment by hxvy0** [comment]
okay i removed cloudflare reverse proxy. now will you add?

**Comment by hxvy0** [comment]
woww without cloudflare so much faster

**Comment by hxvy0** [comment]
add or not?

**Comment by ononoki1** [comment]
There are some issues with your instance. **Please at least fix the first one.** Others can be ignored if you do not mind being ranked lower on searx.space.

**1. Your [TLS](https://cryptcheck.fr/https/futursearch.gq) grade is bad (F). Please at least get an E grade for security.**
2. Your [CSP](https://observatory.mozilla.org/analyze/futursearch.gq) grade is not optimal.
3. You may not configure filtron well. I can still make requests via curl: `curl -L futursearch.gq?q=123`.

After you fix the first issue, we will add your instance.

**Comment by hxvy0** [comment]
oh shit
dont add ok

**Comment by ononoki1** [comment]
The choice is always yours.
