### ISSUE TITLE
Add https://search.konvicts.net

### ISSUE THREAD

**Issue by konvict** [searxng/searx-instances#135]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

use the original docker image with no modification.
CDN : Cloudflare
Server: 3vCPU ,3G RAM, location: RU

**Comment by unixfox** [comment]
Hello,

Like you have probably read, we do not recommend to use cloudflare. Please give proper reasons why you really need to use it.

If you want to protect your instance against the bots, you have already installed the only major component which is filtron, cloudflare will not do much in combating against bots.

**Comment by konvict** [comment]
Hi

Accessing VPSes in China that do not use CDN, the packet loss rate is high,
and the network latency is also high.
So I had to use a CDN. As far as I know, the best free foreign CDN
provider  is Cloudflare.

I will configure my instance to make it more safety.
BTW,where can i find the documents about filtron please?

thanks alot.

Émilien Devos ***@***.***> 于2022年7月23日周六 04:04写道：

**Comment by ononoki1** [comment]
> Accessing VPSes in China that do not use CDN, the packet loss rate is high,
and the network latency is also high.

Thanks for your caring for Chinese users, but unfortunately using Cloudflare often makes the network quality even worse in mainland China, because Cloudflare IPs are big targets, and the connection is usually rate-limited by either ISP or firewall.

If you really care for Chinese users, please use a VPS located in Asia or West US like mine (https://search.ononoki.org). Also it's not wise to compromise **global** users' privacy just for **some** users' _network quality_ (which may not even work).

**Comment by ononoki1** [comment]
@konvict Any update?

**Comment by konvict** [comment]
nope.
it will take days to select a apt VPS provider.
and i will read documents about filtron, searchx, searchxng, it also need time.
so, i'm going to cancel my request.
I'll submit the request again when all the things have be done
thanks alot for your assistance.
