### ISSUE TITLE
Add https://search.vidhukant.xyz

### ISSUE THREAD

**Issue by MikunoNaka** [searxng/searx-instances#136]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [x] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (other rules).

**Comment by ononoki1** [comment]
There are some issues with your instance.

Your [TLS](https://cryptcheck.fr/https/search.vidhukant.xyz) and [CSP](https://observatory.mozilla.org/analyze/search.vidhukant.xyz) grades are not optimal. You can disable DH ciphers (i.e. DHE-RSA-AES128-GCM-SHA256 and DHE-RSA-AES256-GCM-SHA384) to get A+ for TLS. And you can add proper Content-Security-Policy header to improve CSP. An example is here: https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L85=.

Your instance can be added even if the issues above are not fixed. It will just make your instance rank lower on searx.space. Please confirm whether you want to fix them first or just add your instance now.

**Comment by MikunoNaka** [comment]
I have tinkered with my config files to make it better, it still isn't at a very good score but I'll figure it out
so yes please! add my instance.
