### ISSUE TITLE
Add https://saber.tk

### ISSUE THREAD

**Issue by Gamer555DT** [searxng/searx-instances#138]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by unixfox** [comment]
Hi,

We will soon remove the instances with free domains like domains registered on Freenom, see why here: https://github.com/searxng/searx-instances/discussions/225
This doesn't mean that your instance on the public list comes to an end, we would be very happy to keep your instance in the list, we need you to buy a domain and ask for your new domain to be added on the list: https://github.com/searxng/searx-instances/issues.

Here is a website where you can find cheap registrars for buying a domain: https://tld-list.com
