### ISSUE TITLE
Add https://search.robothouse.xyz

### ISSUE THREAD

**Issue by r33zA** [searxng/searx-instances#139]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by tiekoetter** [comment]
@r33zA There is no SearXNG instance active on the provided URL.

**Comment by unixfox** [comment]
> @r33zA There is no SearXNG/SearX instance active on the provided URL.

There is one for me.

https://user-images.githubusercontent.com/4016501/180975354-f64386f3-49a6-4d30-b0c1-d0c05d1242cb.png

**Comment by tiekoetter** [comment]
@unixfox His http site doesn't redirect to the https version. I checked it on my phone first and only copied the fqdn.

**Comment by unixfox** [comment]
@r33zA please add redirect from HTTP to HTTPS

**Comment by ononoki1** [comment]
Close due to lack of reply.
