### ISSUE TITLE
Add https://searx.esmailelbob.xyz

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [searxng/searx-instances#14]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed antibot-proxy or another bot protection.

### Comment

Well, this is my self-hsoted instance of searx, do not expect something fancy or REALLY fast as it's my personal home internet so yeah...i'm trying to help with my limited resources so just do not expect lighting speed

**Comment by unixfox** [comment]
Hello,
When hosting a public instance, you should expect a very high traffic coming to your server. Are you really sure to publicly offer your instance? You could have your home internet not working at all because of the huge bandwidth usage by hundred of users.

**Comment by EsmailELBoBDev2** [comment]
Fair point, Yes i know i have limited resources but i really want to help by self-hosting so fear not! 

I'm stacking on that my instance will be a needle in a haystack. So not a lot of users would use it at the same time. Also I'm looking for ways to improve speed/my internet quota so yeah i hope i would be improved in same time my instance(s) start to grow up and be more known 

So yes i'm really sure
___
PS i want to add that i also have tor ver: http://searx.2syis2nnyytz6jnusnjurva4swlaizlnleiks5mjp46phuwjbdjqwgqd.onion

**Comment by EsmailELBoBDev2** [comment]
updates, well i moved most of public use instances on a vps at hetnzer so i think you would be happy now lol

**Comment by EsmailELBoBDev2** [comment]
You seriously was waiting me to move it in a vps? wow someone really hates self-hosting at home ig

**Comment by unixfox** [comment]
No, I've other things to do in my life apart from maintaining this repository and I just found the time to do it now :).

**Comment by unixfox** [comment]
Hello @EsmailELBoBDev2,

We recently added a new rule that forbid the restriction of users unless this causes an issue with availability of your instance, you can read more about it here: https://github.com/searxng/searx-instances/pull/346

It has come to our attention in this issue #344 that you are restricting users from accessing to your instance with a reason outside of what is allowed by this new rule.

We request you to remove any restriction on your service, or we will have to remove your instance from the public list.

Failure to reply by the 28th May, we will remove your instance from the list.

Thank you for your understanding.

**Comment by EsmailELBoBDev2** [comment]
Yeah sure, add the new rule after I create my ToS. Just remove the instance already. lol
