### ISSUE TITLE
Add https://sh0.it

### ISSUE THREAD

**Issue by xfm99** [searxng/searx-instances#141]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by ononoki1** [comment]
There are some issues with your instance.

1. Your CSP is too strict. Image search works poorly (e.g. https://sh0.it/search?q=test&category_images=on). Here is an example for CSP: https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L85=.
2. Your [TLS](https://cryptcheck.fr/https/sh0.it) grade is not optimal. You can disable DHE-RSA-AES128-GCM-SHA256, DHE-RSA-AES256-GCM-SHA384 and ECDHE-RSA-AES128-SHA to get A+.
3. Your [CSP](https://observatory.mozilla.org/analyze/sh0.it) grade is not optimal. You can deduplicate X-Content-Type-Options and X-XSS-Protection headers to get A+.
4. Your web server only supports HTTP/1.1. We recommend you to support HTTP/2 for better performance. I noticed that you are using NGINX. You can [add _http2_ parameter in `listen` directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen).

Please at least fix the first issue to let users use your instance normally. Other issues can be ignored if you don't mind your instance being ranked lower on searx.space.

**Comment by xfm99** [comment]
hi, i think i have fixed most of the problems

**Comment by unixfox** [comment]
Now we can't do any search on your instance because we receive the error `Rate limit exceeded`. You should fix this issue, we can't add an instance that doesn't work.

**Comment by xfm99** [comment]
problem solved

**Comment by xfm99** [comment]
problem solved thank you
