### ISSUE TITLE
Add https://searx.sirzech.my.id/

### ISSUE THREAD

**Issue by sirzech30** [searxng/searx-instances#147]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by tiekoetter** [comment]
Hi @sirzech30,
some minor things:
1. You are missing two http headers: `X-XSS-Protection` and `X-Content-Type-Options` to reach an A+ rating (check https://observatory.mozilla.org/analyze/searx.sirzech.my.id).
2. Your instance seems to serve SearXNG from the `/searx` path. Is this intended?
