### ISSUE TITLE
https://zonghe.com

### ISSUE THREAD

**Issue by kevinwangsl99** [searxng/searx-instances#15]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (other rules).

### Source code URL

https://github.com/kevinwangsl99/zonghe

**Comment by unixfox** [comment]
Please continue the discussion here: https://github.com/searxng/searx-instances/issues/15
I've reopened the other issue and please reply to my question on this issue: https://github.com/searxng/searx-instances/issues/15
