### ISSUE TITLE
Add https://searx.kujonello.cf/

### ISSUE THREAD

**Issue by kuj0nell0** [searxng/searx-instances#152]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://hub.docker.com/r/vojkovic/searxng

### Comment

I've removed cloudflare's HTTP tracker as described here: https://github.com/searxng/searx-instances/issues/33

**Comment by ononoki1** [comment]
Your [CSP](https://observatory.mozilla.org/analyze/searx.kujonello.cf) grade is not optimal. Besides, you did not configure the limiter plugin well because I can still make request via curl: `curl https://searx.kujonello.cf/search?q=test`.

Your instance can be added even if the issues above are not fixed. It will just make your instance rank lower on searx.space. Please confirm whether you want to fix these issues first or add your instance now.

**Comment by kuj0nell0** [comment]
@ononoki1 I've fixed the limiter plugin (I hope so; i can't make request as you described). I've also implemented all http headers that were affecting my CSP grade (like shown [here](https://infosec.mozilla.org/guidelines/web_security#x-frame-options) ).

https://cloud.kujonello.cf/s/X8EwpmQfd7fdQSF 
https://cloud.kujonello.cf/s/kNDgYz6fyBiBLqG

**Comment by kuj0nell0** [comment]
The last two links are screenshots from curl and http headers

**Comment by ononoki1** [comment]
The limiter plugin works well now. But your CSP header is not good. You can use this one: https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L85.

**Comment by kuj0nell0** [comment]
> The limiter plugin works well now. But your CSP header is not good. You can use this one: https://github.com/searxng/searxng-docker/blob/f2f9e2ad086c68443c3457a82cf2e368aaa4bc99/Caddyfile#L85.

How about now? Switched my caddyfile

**Comment by ononoki1** [comment]
> How it's now? Switched my caddyfile

You are using openresty (nginx), not caddy. And your CSP header does not change, still `img-src 'self' data: ;`.

**Comment by kuj0nell0** [comment]
> > How it's now? Switched my caddyfile
> 
> You are using openresty (nginx), not caddy. And your CSP header does not change, still `img-src 'self' data: ;`.

ah, yea

I think now CSP works https://observatory.mozilla.org/analyze/searx.kujonello.cf
Will have to fight with SRI haha

**Comment by ononoki1** [comment]
> Will have to fight with SRI haha

Make sure `static_path` and `templates_path` in _settings.yml_  are both empty string.

**Comment by kuj0nell0** [comment]
I've done that, and now Mozilla Observatory gives my instance A+ https://observatory.mozilla.org/analyze/searx.kujonello.cf
I think the instance is ready to be available trough public list.

**Comment by unixfox** [comment]
Hi,

We will soon remove the instances with free domains like domains registered on Freenom, see why here: https://github.com/searxng/searx-instances/discussions/225
This doesn't mean that your instance on the public list comes to an end, we would be very happy to keep your instance in the list, we need you to buy a domain and ask for your new domain to be added on the list: https://github.com/searxng/searx-instances/issues.

Here is a website where you can find cheap registrars for buying a domain: https://tld-list.com
