### ISSUE TITLE
Add http://searx.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [searxng/searx-instances#154]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed another bot protection.

### Comment

it's my tor version of searx.esmailelbob.xyz

**Comment by ononoki1** [comment]
You should use `Edit an existing searx instance` issue template instead of `Add a new instance`.

**Comment by EsmailELBoBDev2** [comment]
but I want to add new instance not replace links

**Comment by EsmailELBoBDev2** [comment]
anyways. done https://github.com/searxng/searx-instances/issues/155

**Comment by ononoki1** [comment]
> but I want to add new instance not replace links

As the commit b03ce11f5dabfddbe483645e7cad650377fbe933 shows, it didn't replace your clearnet link. So just relax.

**Comment by EsmailELBoBDev2** [comment]
> So just relax.

Was making sure :-p
