### ISSUE TITLE
Add https://www.higgssearch.com

### ISSUE THREAD

**Issue by flabbydino** [searxng/searx-instances#156]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by tiekoetter** [comment]
@flabbydino Your instance has a bot protection (probably the limiter plugin) enabled.
Note that your root domain (higgssearch.com) does not resolve to an A or AAAA record.

I will add your instance though.

**Comment by unixfox** [comment]
Instance removed in https://github.com/searxng/searx-instances/commit/98d67da24447dade0b2f6b2fcf901637eb27c1b3 due to bad uptime.

Uptime went below 90%: https://github.com/searxng/searx-instances-uptime/blob/005c35fe7eeffb2c6aebeb7e281f30a60b0103c1/api/www-higgssearch-com/uptime-month.json
