### ISSUE TITLE
Delete <searx instance url>

### ISSUE THREAD

**Issue by 0x49e396** [searxng/searx-instances#158]
Instance added by the issue ??

Hey why is it not working?

**Comment by ononoki1** [comment]
Close due to off-topic.

**Comment by 0x49e396** [comment]
Why did you close it? It ain't working so it isn't fixed.

**Comment by 0x49e396** [comment]
It's still not working

**Comment by unixfox** [comment]
Please create a new issue on Github, you didn't enter an URL in the title nor did you filled the template: https://github.com/searxng/searx-instances/issues/new/choose

**Comment by 0x49e396** [comment]
I don't know what I need to choose. I use farside.link for searxng and it doesn't work with some links. I got linked to this because you're the admins of the searxng list?

**Comment by return42** [comment]
please contact faireside.link / here you are wrong

**Comment by unixfox** [comment]
Please open an issue on https://github.com/benbusby/farside/issues
