### ISSUE TITLE
Add  https://searxng.cf

### ISSUE THREAD

**Issue by TheCaduceus** [searxng/searx-instances#159]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I do not track the users of my instance with any analytics or tracking software.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/searxng/searxng

**Comment by ononoki1** [comment]
Your TLS (https://cryptcheck.fr/https/searchxng.cleverapps.io) and CSP (https://observatory.mozilla.org/analyze/searchxng.cleverapps.io) grades are not optimal.

Your instance can be added even if the issues above are not fixed. It will just make your instance rank lower on searx.space. Please confirm whether you want to fix them first or just add your instance now.

**Comment by TheCaduceus** [comment]
@ononoki1 Umm, then just wait. Let me do this with custom domain and Cloudflare for Bot Protection

**Comment by return42** [comment]
> and Cloudflare for Bot Protection

why do so many people think that they need CF for bot protection?  .. I have my instance running since years .. before I used filtron, now I use the limiter ... the bot protection of SearXNG works flawless .. the old one (filtron) and the new one (limiter).

**Comment by TheCaduceus** [comment]
@ononoki1 Now you can add https://searxng.cf

**Comment by ononoki1** [comment]
Your TLS (https://cryptcheck.fr/https/searxng.cf) and CSP (https://observatory.mozilla.org/analyze/searxng.cf) grades are not optimal.

Besides, you may not configure limiter plugin well because I can still make requests via curl: `curl -L searxng.cf?q=123`.

The issues above can be ignored if you do not mind your instance ranked lower on searx.space. But you must disable Cloudflare or give proper reason for using it (bot protection is not a proper one), otherwise your instance will not be added.
