### ISSUE TITLE
Add https://icanfindit.online

### ISSUE THREAD

**Issue by rattfieldnz** [searxng/searx-instances#165]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Source code URL

https://github.com/rattfieldnz/searxng-docker

### Comment

I have recently got a Linode server, and have reinstalled SearXNG on there. I intend to keep this instance running for the long term. Linode has easier to understand pricing than AWS.

**Comment by unixfox** [comment]
Hi, your instance was previously removed from the list for bad uptime: https://github.com/searxng/searx-instances/commit/988998e6866f90f54cbc2f5c8860bbf0b6e7b77d

Like we have to discussed in https://github.com/searxng/searx-instances/discussions/150, we will add your instance only if it has a good uptime after 1 week, at around 95%.

So you will have to wait 1 week for your instance to be added and if it has a good uptime at the end of the 1-week then it will be added.
