### ISSUE TITLE
Add https://search.rhscze.cf

### ISSUE THREAD

**Issue by rhsCZ** [searxng/searx-instances#168]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

i've tested on https://cryptcheck.fr/https/search.rhscze.cf, but i can't retest now after modifing apache2 config - maybe later, so i'll hopefully be on at least A or A+ grade. also got a+ on https://observatory.mozilla.org/analyze/search.rhscze.cf

**Comment by ononoki1** [comment]
I cannot get access to your site now. It shows `500 Internal Server Error`.

**Comment by rhsCZ** [comment]
sorry, it's my fault i didn't checked before posting, i had something misconfigured during configuration for security. but after reinstall it should work fine now.

**Comment by tiekoetter** [comment]
@rhsCZ Any reason your instance only supports 3 different search languages?

**Comment by rhsCZ** [comment]
@tiekoetter no, i forgot to edit. i added now all missing languages as well. Thanks for mentioning that.

**Comment by ononoki1** [comment]
Your web server only supports HTTP/1.1. It's recommended to enable HTTP/2 support for better performance. Would you like to do that? Or you can just let me add your instance now. What do you think?

**Comment by rhsCZ** [comment]
I had to use google, because i found out, that legacy php apache module was using mpm_prefetch which blocks using http/2. I fixed it now and i hope there shoudln't be any more problems. i checked via developer tools, so now it should use http/2.
