### ISSUE TITLE
Add https://trydex.tk/searxng

### ISSUE THREAD

**Issue by LencoDigitexer** [searxng/searx-instances#169]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/f5ociety/Trydex

**Comment by tiekoetter** [comment]
@LencoDigitexer 
Some things to note:
1. The instance redirects to the `/searxng` path.
2. The instance lets the user connect directly to `icons.duckduckgo.com` regardless of the image proxy setting

This is ok but you should maybe look into proxying the requests to `icons.duckduckgo.com` for a better user privacy.

**Comment by unixfox** [comment]
Hi,

We will soon remove the instances with free domains like domains registered on Freenom, see why here: https://github.com/searxng/searx-instances/discussions/225
This doesn't mean that your instance on the public list comes to an end, we would be very happy to keep your instance in the list, we need you to buy a domain and ask for your new domain to be added on the list: https://github.com/searxng/searx-instances/issues.

Here is a website where you can find cheap registrars for buying a domain: https://tld-list.com
