### ISSUE TITLE
serx.cf: Hiding the analytics software

### ISSUE THREAD

**Issue by unixfox** [searxng/searx-instances#17]
Hello @inoblue,

You are trying to circumvent the JS resources detection system by searx.space on your instance: https://serx.cf by not including the Matomo JS script only when the check.searx.space do a request.

Here is a proof.
The HTML head of a normal visitor:
```html
<head>
    <meta charset="UTF-8" />
    <meta name="description" content="searx - a privacy-respecting, hackable metasearch engine" />
    <meta name="keywords" content="searx, search, search engine, metasearch, meta search" />
    <meta name="generator" content="searx/1.0.0">
    <meta name="referrer" content="no-referrer">
    <meta name="viewport" content="width=device-width, initial-scale=1 , maximum-scale=2.0, user-scalable=1" />
    <title>serx.cf</title>
    <link rel="stylesheet" href="/static/themes/oscar/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="/static/themes/oscar/css/pointhi.min.css" type="text/css" />

    <link rel="shortcut icon" href="/static/themes/oscar/img/favicon.png" />


    <link title="serx.cf" type="application/opensearchdescription+xml" rel="search" href="/opensearch.xml?method=GET&amp;autocomplete="/>
    <noscript>
        <style type="text/css">
            .tab-content > .active_if_nojs, .active_if_nojs {display: block !important; visibility: visible !important;}
            .margin_top_if_nojs {margin-top: 20px;}
            .hide_if_nojs {display: none !important;overflow: hidden !important;}
            .disabled_if_nojs {pointer-events: none; cursor: default; text-decoration: line-through;}
        </style>
    </noscript>
    <script src="/static/m.js"></script><noscript><p><img src="https://serx.cf/m/m.php?idsite=10&amp;rec=1" style="border:0;" alt="" /></p></noscript>
</head>
```

And the HTML head from check.searx.space:
```html
<head>
    <meta charset="UTF-8" />
    <meta name="description" content="searx - a privacy-respecting, hackable metasearch engine" />
    <meta name="keywords" content="searx, search, search engine, metasearch, meta search" />
    <meta name="generator" content="searx/1.0.0">
    <meta name="referrer" content="no-referrer">
    <meta name="viewport" content="width=device-width, initial-scale=1 , maximum-scale=2.0, user-scalable=1" />
    <title>serx.cf</title>
    <link rel="stylesheet" href="/static/themes/oscar/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="/static/themes/oscar/css/pointhi.min.css" type="text/css" />

    <link rel="shortcut icon" href="/static/themes/oscar/img/favicon.png" />


    <link title="serx.cf" type="application/opensearchdescription+xml" rel="search" href="/opensearch.xml?method=GET&amp;autocomplete="/>
    <noscript>
        <style type="text/css">
            .tab-content > .active_if_nojs, .active_if_nojs {display: block !important; visibility: visible !important;}
            .margin_top_if_nojs {margin-top: 20px;}
            .hide_if_nojs {display: none !important;overflow: hidden !important;}
            .disabled_if_nojs {pointer-events: none; cursor: default; text-decoration: line-through;}
        </style>
    </noscript>
</head>
```

Note: `/static/m.js` is not present on check.searx.space.

Can you either not excluding the JS script for Matomo analytics when check.searx.space do a request or remove Matomo analytics on your instance?

Thank you.

**Comment by inoblue** [comment]
Sorry. It seems that the problem is with nginx's proxy cache. I set proxy_cache_key to $remote_addr$request_uri and proxy_cache_valid to 90d, so when the same user searches the same thing in 3 months, nginx returns the same page instead of sending query to backend searx. So the reason should be that when the instance first became public, I removed matomo code for about half a day, then added it back. I think check.searx.space might visit the site during that period, so nginx cached the vanilla version, while other users (with different ip addresses) are not influenced.

**Comment by unixfox** [comment]
Thank you for the explanations @inoblue.

We don't actually recommend caching the HTML pages because this can reduce the user privacy as all the queries done by the users will be stored in memory/disk.

**Comment by return42** [comment]
> so when the same user searches the same thing in 3 months, nginx returns the same page

And when the user searches some news, he will get 90 days the same old news :confused:

**Comment by inoblue** [comment]
> > so when the same user searches the same thing in 3 months, nginx returns the same page
> 
> And when the user searches some news, he will get 90 days the same old news

No. The cache has conditions. If the search category is news (means `category_news=on`) or search query contains `random`, `user agent` (which obviously shouldn't be cached), the cache will be bypassed. :)

**Comment by return42** [comment]
"news" was just an example / most users expect up-to-date results for a query / take "covid" or any other query .. or when an engine in SearXNG is fixed, a result from a broken engine is cached .. 

> Anyway, the cache time is reduced to 1h now, so there's no need to worry.

I discussed it here to show others coming around that it is not a good idea to cache (over a long period).
