### ISSUE TITLE
Edit https://searx.fi

### ISSUE THREAD

**Issue by RoyTakanen** [searxng/searx-instances#171]
Instance added by the issue #103.

Add tor/onion domain: http://searxfilowxokbogygrigir4wqxfxqzuxofxgdon7dg6rsii4yxzytyd.onion/

**Comment by ononoki1** [comment]
It's recommended to add http header `Onion-Location: http://searxfilowxokbogygrigir4wqxfxqzuxofxgdon7dg6rsii4yxzytyd.onion$request_uri` so that users can be redirected to onion site automatically when visiting the clearnet link.

**Comment by RoyTakanen** [comment]
Thanks. I added that.
