### ISSUE TITLE
Add https://search.rowie.at

### ISSUE THREAD

**Issue by rowie** [searxng/searx-instances#173]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by unixfox** [comment]
@rowie

A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st January 2024. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by rowie** [comment]
Damn... sorry for the late reply... but I have to filter my instance.
Too many requests have made it unusable... and constantly solving captchas isn't really my thing either. Is there perhaps a useful guide on how to better protect my instance or make it usable?

br,
rowie

**Comment by rowie** [comment]
i could deploy more then once instance if needed ... only ipv4 but in different countries

**Comment by vojkovic** [comment]
I love Germany, Austria and Switzerland but unfortunately you can't restrict access to just those three countries! The bot situation is complex and defending against them seems to be a moving target. Some instances are having success using a l7 bot detection like Anubis, although I personally recommend against this as users with javascript or webworkers disabled will be blocked.

An alternative would be to use multiple instances or use rotate your IPs often.

You're more than welcome to make a new issue to add your instance again once you have decided you're ready. Once you do this, I can also invite you to come discuss the issue with us in the searxng public instance maintainers matrix group.

**Comment by rowie** [comment]
done!

**Comment by rowie** [comment]
> I love Germany, Austria and Switzerland but unfortunately you can't restrict access to just those three countries! The bot situation is complex and defending against them seems to be a moving target. Some instances are having success using a l7 bot detection like Anubis, although I personally recommend against this as users with javascript or webworkers disabled will be blocked.
> 
> An alternative would be to use multiple instances or use rotate your IPs often.
> 
> You're more than welcome to make a new issue to add your instance again once you have decided you're ready. Once you do this, I can also invite you to come discuss the issue with us in the searxng public instance maintainers matrix group.

I have a Firewal in front of my servers in the datacenter with geo-blocking. I had restricted them to the region of the three countries.
From now on, my instance is accessible again from anywhere.
