### ISSUE TITLE
https://search.neet.works

### ISSUE THREAD

**Issue by rawhide-kobayashi** [searxng/searx-instances#18]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by return42** [comment]
@rawhide-kobayashi please update your instance

**Comment by rawhide-kobayashi** [comment]
I gotchu b

**Comment by return42** [comment]
@rawhide-kobayashi FYI your instance has not been updated since a longer time / its recommended to update regularly.
