### ISSUE TITLE
Delete https://searx.feneas.org

### ISSUE THREAD

**Issue by austinhuang0131** [searxng/searx-instances#19]
Instance added by https://github.com/searxng/searx-instances/commit/43e5ddc0bf4988994854357481a4df0330b05c1a

I am not the instance owner.

---

See [here](https://git.feneas.org/feneas/association/-/raw/master/comms/dissolving-the-association-2022-01-09.txt), which is linked on the [homepage](https://feneas.org):

> * The timeline of shutting down the services is as follows:
>   * [...]
>   * The following services will be shut down on or soon after the 1st of March (UTC morning time). This includes:
>     * [...]
>     * Searx (searx.feneas.org)

Or you could wait till March 1st.

**Comment by unixfox** [comment]
Thanks for notifying us.
