### ISSUE TITLE
Delete https://searxng.tordenskjold.de

### ISSUE THREAD

**Issue by CaptainTordenskjold** [searxng/searx-instances#196]
Instance added by the issue #86

**Comment by tiekoetter** [comment]
May I ask why you want it to be deleted?

**Comment by CaptainTordenskjold** [comment]
Since I'll be traveling for a long time soon, I can't actively take care of the instance for the time being in case something doesn't work. Therefore I would prefer that my instance is not listed publicly for the time being. I probably won't continue to rent the servers in the meantime, so I will re-host it under the same domain later.
