### ISSUE TITLE
Add https://search.drivet.xyz

### ISSUE THREAD

**Issue by GhostSlayer** [searxng/searx-instances#200]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

custom logo becuz it looks 5/50 lol

**Comment by ononoki1** [comment]
Hi! Your [TLS](https://cryptcheck.fr/https/search.drivet.xyz) and [CSP](https://observatory.mozilla.org/analyze/search.drivet.xyz) grade is not optimal. You can use HSTS and CSP header to get A+ for both.

The TLS and CSP issue can be ignored if you do not mind being ranked lower on searx.space. If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

**Comment by unixfox** [comment]
It is obviously critical as the users of your instance should not have a degraded security, that's why we rank lower the instances that are negligent on security.

**Comment by GhostSlayer** [comment]
fixed

**Comment by GhostSlayer** [comment]
While im not too familiar with CSP stuff, i will try to figure out the best settings to get a passed on CSP test

**Comment by ononoki1** [comment]
> While im not too familiar with CSP stuff, i will try to figure out the best settings to get a passed on CSP test

FYI here is an example https://github.com/searxng/searxng-docker/blob/d4f06df911e91803d6af48b8f0e060f08429b767/Caddyfile#L85

**Comment by GhostSlayer** [comment]
Fixed, now it passes on both TLS and CSP

**Comment by GhostSlayer** [comment]
Hey, my SearXNG instance had a short outage. I switched servers and its now available

**Comment by unixfox** [comment]
Added back in https://github.com/searxng/searx-instances/commit/41e994226a44266e33bda5a4f465ef262f94f988
