### ISSUE TITLE
Add https://searx.juancord.xyz

### ISSUE THREAD

**Issue by rywng** [searxng/searx-instances#205]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by ononoki1** [comment]
Hi @JuanCldCmt, your [TLS](https://cryptcheck.fr/https/searx.juancord.xyz) and [CSP](https://observatory.mozilla.org/analyze/searx.juancord.xyz) grade is not optimal. You can enable `ECDHE-RSA-AES128-GCM-SHA256`, `ECDHE-RSA-AES256-GCM-SHA384` and `ECDHE-RSA-CHACHA20-POLY1305` ciphers for TLSv1.2 to get A+ on TLS, and add CSP header like [this](https://github.com/searxng/searxng-docker/blob/d4f06df911e91803d6af48b8f0e060f08429b767/Caddyfile#L85) to get A+ on CSP.

However, these grades can be ignored if you do not mind being ranked lower on [searx.space](https://searx.space). If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

**Comment by JuanCldCmt** [comment]
Hello, I enabled TLS1.3 only, but https://cryptcheck.fr/https/searx.juancord.xyz shows TLS is not supported. Is this a bug, or I'm supposed to enable TLS1.2 (with your recommended ciphers)?

**Comment by JuanCldCmt** [comment]
I think you can add my instance now, if TLS1.3 only is allowed, and I will work on CSP headers once I have some time, thanks!

**Comment by unixfox** [comment]
> Hello, I enabled TLS1.3 only, but https://cryptcheck.fr/https/searx.juancord.xyz shows TLS is not supported. Is this a bug, or I'm supposed to enable TLS1.2 (with your recommended ciphers)?

Yes please enable TLS1.2 or we can't scan the TLS security of your instance.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by JuanCldCmt** [comment]
> A new big change has been introduced 🎉!
> 
> Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761
> 
> We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.
> 
> We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.
> 
> Feel free to ask here if you have any troubles setting up this new parameter.

Hello, I've already added the parameter, is there anything else I have to do? thanks

**Comment by return42** [comment]
@rywng your instance returns 502 Bad Gateway .. can you please fix the issue / thanks :+1:

**Comment by rywng** [comment]
The outage was reported in https://github.com/searxng/searx-instances/discussions/623
Now it's working :)

**Comment by unixfox** [comment]
Thank you @rywng. @return42 was not aware of the "downtime" section in github discussions.

**Comment by return42** [comment]
@rywng your instance has an issue with the favicons / I guess its related to the CSP header.

**Comment by rywng** [comment]
Hi, thanks for checking. on my computer it's always like this, so I never noticed:

![Image](https://github.com/user-attachments/assets/ff477868-b562-4f34-8f7d-c4b148e9602c)

Currently, I'm busy with school. I'll have time to look into this in around 2 weeks.

Sorry for the inconvenience, and I will respond again when I have fixed the problem.

**Comment by vojkovic** [comment]
Hi @rywng - searx.juancord.xyz has been down for roughly a week - its been returning 502s.

https://github.com/searxng/searx-instances-uptime/issues/10514

Could you please address this so that we don't need to remove your instance from the list? Cheers

**Comment by vojkovic** [comment]
https://github.com/searxng/searx-instances/commit/cf9fad6093804b65814b43621a253853ce1ca38b
