### ISSUE TITLE
Add https://searxng.gigarange.org

### ISSUE THREAD

**Issue by Gigarange** [searxng/searx-instances#214]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/searxng/searxng.git

**Comment by ononoki1** [comment]
Please give proper reason for using Cloudflare. Otherwise, your instance cannot be added.

**Comment by Gigarange** [comment]
Currently being hosted from home network so its to protect against ddos and leaking my IP. Searxng is run as a HA service with load balancing through traefik so downtime should be a minimum.

**Comment by ononoki1** [comment]
FYI https://github.com/searxng/searx-instances/issues/56#issuecomment-1120249048

> Offering a public service requires to invest time and money. Or else people aren't going to have a good experience on your instance.
>
> It takes some responsibilities to run a public service, it's not just install searx(ng) and that's it.

**Comment by Gigarange** [comment]
Thank you for the feedback, I'll try again when I can afford to host it remotely.
