### ISSUE TITLE
Add https://google.com-l.ink

### ISSUE THREAD

**Issue by Felmon** [searxng/searx-instances#219]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by ononoki1** [comment]
Hi @Felmon, your [TLS](https://cryptcheck.fr/https/google.com-l.ink) grade is only F. Please get at least E for your instance to be added.

**Comment by ononoki1** [comment]
Close due to lack of reply.

**Comment by Felmon** [comment]
How is this TLS grade generally affected? I see that there are also many Fs in the instance.

**Comment by Felmon** [comment]
[[Qualys SSL report](https://www.ssllabs.com/ssltest/analyze.html?d=www.futursearch.gq)](https://www.ssllabs.com/ssltest/analyze.html?d=google.com-l.ink)   is B.

**Comment by tiekoetter** [comment]
Refer to https://cryptcheck.fr/https/google.com-l.ink

**Comment by Felmon** [comment]
![image](https://user-images.githubusercontent.com/19621032/199433820-6ca23a2b-35db-4ff7-9d1f-2402976244d0.png)
But @ononoki1 don't just look at cryptcheck, you also trust Qualys' results.    And https://cryptcheck.fr/https/www.google.com  also just is a F.   So why do you trust the results of cryptcheck? Because it's French?

**Comment by unixfox** [comment]
> ![image](https://user-images.githubusercontent.com/19621032/199433820-6ca23a2b-35db-4ff7-9d1f-2402976244d0.png) But @ononoki1 don't just look at cryptcheck, you also trust Qualys' results. And [cryptcheck.fr/https/www.google.com](https://cryptcheck.fr/https/www.google.com) also just is a F. So why do you trust the results of cryptcheck? Because it's French?

See https://github.com/searxng/searx-space/issues/10#issuecomment-572003677

**Comment by return42** [comment]
@Felmon do you think it is a good idea to use google's trademarks in your [instance](https://google.com-l.ink/)? ...

![grafik](https://user-images.githubusercontent.com/554536/199474208-67fc0a6a-afc6-40dc-83e6-d070d2547983.png)

**Comment by unixfox** [comment]
True we can't add instances that are infringing some copyrights.
