### ISSUE TITLE
Add https://www.futursearch.gq

### ISSUE THREAD

**Issue by hxvy0** [searxng/searx-instances#220]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

Hi, I'm Enes from Turkey. Can you add my istance?

Url: www.futureddit.gq 

Cloudflare: Yes 

Server location: Italy 

I won't tell you why I use Cloudflare because it's a secret, I hope that you appreciate.

**Comment by unixfox** [comment]
Hi, unfortunately we can't add your instance if you don't give a proper reason for using cloudflare.

**Comment by hxvy0** [comment]
Sorry but i cant say

**Comment by ononoki1** [comment]
Sorry, but without a proper reason, your instance cannot be added.

**Comment by hxvy0** [comment]
> Sorry, but without a proper reason, your instance cannot be added.

Ok im removing cloudflare right now please wait

**Comment by hxvy0** [comment]
> > Sorry, but without a proper reason, your instance cannot be added.
> 
> Ok im removing cloudflare right now please wait

Removed

**Comment by ononoki1** [comment]
Hi @hxvy0, I just found that your instance is libreddit instead of searx(ng). Please raise an issue in corresponding repo :)

**Comment by hxvy0** [comment]
And i typed wrong location is united states

**Comment by hxvy0** [comment]
oh again wrong istance is https://www.futursearch.gq sorry for that

**Comment by hxvy0** [comment]
I gave up on my ddos protection for it to be added, can you answer? @ononoki1

**Comment by hxvy0** [comment]
did you add ?

**Comment by ononoki1** [comment]
[CryptCheck](https://cryptcheck.fr/https/www.futursearch.gq) cannot correctly test your TLS, so I use [Qualys SSL report](https://www.ssllabs.com/ssltest/analyze.html?d=www.futursearch.gq). According to the result, please disable TLSv1.0 and TLSv1.1 for your instance to be added.

**Comment by hxvy0** [comment]
> [CryptCheck](https://cryptcheck.fr/https/www.futursearch.gq) cannot correctly test your TLS, so I use [Qualys SSL report](https://www.ssllabs.com/ssltest/analyze.html?d=www.futursearch.gq). According to the result, please disable TLSv1.0 and TLSv1.1 for your instance to be added.

how to ?

**Comment by hxvy0** [comment]
![image](https://user-images.githubusercontent.com/85783692/198677249-aee2e2cd-34ba-46c5-a103-9e726c11dd7f.png)
already browsers disabling tls 1 and 1.1

**Comment by hxvy0** [comment]
![image](https://user-images.githubusercontent.com/85783692/198678089-818cdf04-a13b-424a-9500-e0fb0bd06675.png)

**Comment by hxvy0** [comment]
its already support tls 1.3

**Comment by ononoki1** [comment]
> already browsers disabling tls 1 and 1.1

Not browser. I mean your server.

**Comment by unixfox** [comment]
Please stop posting multiple messages in a row. Just edit your previous message if it's a recent one.

Sorry we cannot add your instance because it is hosted on an ephemeral hosting provider called repl.it which is not designed to host production services but instead development websites and more.

**Comment by hxvy0** [comment]
> Please stop posting multiple messages in a row. Just edit your previous message if it's a recent one.
> 
> Sorry we cannot add your instance because it is hosted on an ephemeral hosting provider called repl.it which is not designed to host production services but instead development websites and more.
> 
> Reopen this github issue if you have switch to a hosting provider ready for production services.

But its boosted repl. And its so fast i paid for it

**Comment by hxvy0** [comment]
> > already browsers disabling tls 1 and 1.1
> 
> Not browser. I mean your server.

Yea i know

**Comment by hxvy0** [comment]
asd
