### ISSUE TITLE
Delete https://searx.zimro.xyz

### ISSUE THREAD

**Issue by ziimro** [searxng/searx-instances#221]
Instance added by the issue  #217 
I have observed that after the addition of my instance to searx.space, my instance returns "too many requests" after the search querry. I will be fixing that issue

**Comment by unixfox** [comment]
Turn off the limiter for now.

**Comment by ziimro** [comment]
> Turn off the limiter for now.

i want to keep the limiter on, ill fixup my nginx config and then readd the instance
