### ISSUE TITLE
Add https://searx.tuxcloud.net

### ISSUE THREAD

**Issue by fgossel** [searxng/searx-instances#228]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

Dear maintainers, can you add back my instance so that good people can use it again and find it more easily? 
I am not planning any more maintenance in the foreseeable future.
Merci

**Comment by unixfox** [comment]
Hi,
The usual procedure for adding back an instance that got removed from the list is that you will have to wait for 1 week before we add your instance. If after 1 week, your instance has more than 95% of uptime it is added back to the list.
