### ISSUE TITLE
Add https://searx.delicta.pp.ua

### ISSUE THREAD

**Issue by DziubaMaksym** [searxng/searx-instances#231]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by ononoki1** [comment]
Hi @DziubaMaksym, your [TLS](https://cryptcheck.fr/https/searx.delicta.pp.ua) and [CSP](https://observatory.mozilla.org/analyze/searx.delicta.pp.ua) grades are not optimal. If you want to fix these issues before adding your instance to searx.space, just do it and notify us when finished. Otherwise, tell us you do not want to fix them and we will add your instance now.

**Comment by DziubaMaksym** [comment]
Hi @ononoki1 , I don't want to fix them right now. Maybe in the future, I'll have more time for it.

**Comment by unixfox** [comment]
There is an issue with your instance, the CSP header says any CSP violations will be redirected to an example domain:
```
content-security-policy: script-src 'strict-dynamic' 'nonce-rAnd0m123' 'unsafe-inline' http: https:; object-src 'none'; base-uri 'none'; require-trusted-types-for 'script'; report-uri https://csp.example.com;
```
