### ISSUE TITLE
Incorrect TLS rank for https://searx.work

### ISSUE THREAD

**Issue by ice9smart** [searxng/searx-instances#232]
While [CryptCheck](https://cryptcheck.fr/https/searx.work) gives A+, searx.space shows `E, A+`.

This phenomenon has lasted for about a week (start from the moment I change domain from serx.ml to searx.work #229). And it also shows surprising low search response time (0.080s when I raise this issue). I guess there is something wrong with searx.space's DNS resolution?

**Comment by unixfox** [comment]
That's indeed very strange, @dalf any ideas?

**Comment by dalf** [comment]
Problably a cache issue: I've checked directly on the server ([cryptcheck-backend](https://github.com/dalf/cryptcheck-backend)) and the grades are A+.
So I have deleted the cache: searx.space is going to show the update in few hours.
If this fix the issue then it's a cache expiration issue.

In searx.spae, searx.works resolves to:
* 2001:bc8:62c:26::1
* 163.172.156.229

**Comment by unixfox** [comment]
Seems to be fixed.

**Comment by ononoki1** [comment]
Seems to be fixed.
