### ISSUE TITLE
Add https://searxng.au

### ISSUE THREAD

**Issue by wale** [searxng/searx-instances#233]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Source code URL

https://github.com/searxng/searxng

### Comment

Was previously added in #78, but was removed a few months[?] later. I have fixed all issues mentioned in the original issue.

**Comment by wale** [comment]
I had done some maintenance before creating this issue, because of that, I do not plan on having any planned maintenance any time soon.

**Comment by wale** [comment]
I had successfully done maintenance on the server before creating this issue, which means, I do not plan to have any maintenance any time soon.

**Comment by wale** [comment]
I successfully did some maintenance on this SearxNG instance before creating this issue.

**Comment by unixfox** [comment]
We recently added a bunch of rules including a requirement for 90% of uptime per month.

On the 11 of September your instance went below 90% of uptime so we removed it.

**Comment by unixfox** [comment]
As usual we will wait 1 week before adding your instance, after 1 week if you have more than 95% of uptime on your instance we add it back.

Your instance has been added for manual tracking in https://github.com/searxng/searx-instances-uptime/commit/39f0a5deac5921cfc751ae2c7e6e9c73f14251a7

**Comment by wale** [comment]
Bumping this issue, as a week has passed and searxng.au has gotten 100% uptime.

**Comment by return42** [comment]
@wale please update your instance
