### ISSUE TITLE
Add https://searx.ebnar.xyz

### ISSUE THREAD

**Issue by catfluoride** [searxng/searx-instances#24]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

Almost all Google's upstream engines are disabled (or they will be) by choice. Also, Amazon's results are not shown, because they pollute the results with lots of entries from different geographic domains.

**Comment by unixfox** [comment]
Your instance is not working. I get too many redirects.

**Comment by catfluoride** [comment]
Yes, because I messed up something while installing filtron... Grrr...

Inputting direct search string works, though

https://searx.ebnar.xyz/search?q=searx

I'll try to fix it later. Sorry.

**Comment by catfluoride** [comment]
Fine, now it works.

Nonetheless, I need to remove the following directive from the searxng.conf ini tht filtron creates

`   #proxy_set_header   X-Script-Name    /;`

to make it work.

Any advice is welcome.
