### ISSUE TITLE
Edit https://searx.ebnar.xyz

### ISSUE THREAD

**Issue by catfluoride** [searxng/searx-instances#249]
Instance added by the issue https://github.com/searxng/searx-instances/issues/24#issue-1137140883

Could you please change the https://searx.ebnar.xyz instance URL to https://searx.catfluori.de ?

Thanks a lot in advance.

**Comment by unixfox** [comment]
Hello,

Your instance have been removed from the official list for using cloudflare which is against the rules: https://github.com/searxng/searx-instances/blob/master/.github/ISSUE_TEMPLATE/add-instance.yaml

**Comment by catfluoride** [comment]
Hi! Yes, my apologies. I had activated DNS proxy and WAF to make a couple of tests and forgot to disable it afterwards.

It should be fixed now (proxy disabled, no WAF) and I'm just usinc CF DNS (which is nos against the rule, I guess?). Please, reenable my instance it if possible. 

Thanks a lot in advance.

**Comment by unixfox** [comment]
Please create a new instance request: https://github.com/searxng/searx-instances/issues/new/choose

That's the usual process when an instance is removed from the list.

**Comment by catfluoride** [comment]
Ok, fine. Thanks a lot.
