### ISSUE TITLE
Add https://sx.fukt.lol

### ISSUE THREAD

**Issue by iotalol** [searxng/searx-instances#259]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

Not requirements but:
Server is colocated on my own rack
Server is running with Full Disk Encryption (luks)

**Comment by ononoki1** [comment]
Hi @iotalol, your [TLS](https://cryptcheck.fr/https/sx.fukt.lol) grade is not optimal. Please note that you must get at least an E on TLS for your instance to be added.

**Comment by iotalol** [comment]
> Hi @iotalol, your [TLS](https://cryptcheck.fr/https/sx.fukt.lol) grade is not optimal. Please note that you must get at least an E on TLS for your instance to be added.

How would I improve my TLS grade?

**Comment by unixfox** [comment]
Search on the internet on how to do it. There are dozens of tutorials. If you don't find anything come back here for help...

**Comment by iotalol** [comment]
I have figured out how to upgrade my SSL it should now have a better 
grade.

**Comment by iotalol** [comment]
> I have figured out how to upgrade my SSL it should now have a better grade.

Also see https://www.ssllabs.com/ssltest/analyze.html?d=sx.fukt.lol
and https://observatory.mozilla.org/analyze/sx.fukt.lol

Cheers, iota
