### ISSUE TITLE
Add https://baresearch.org

### ISSUE THREAD

**Issue by CameronMunroe** [searxng/searx-instances#260]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by CameronMunroe** [comment]
Please check and confirm.

**Comment by unixfox** [comment]
Perfect, I do confirm it's ok. If you go https://baresearch.org/config, you can see `public_instance: true`

**Comment by CameronMunroe** [comment]
Today, we made an IP change and moved baresearch to a new provider. This is because our old provider is doing a migration and caused us to rebuild our environment. All previous settings are still in effect, and we expect Baresearch to be working like before. 

We wanted to make this post (here) as record of this change in case any worry about the sudden change.

**Comment by vojkovic** [comment]
@CameronMunroe Hey! Thanks for keeping your searxng instance well maintained over the years. Just to let you know that your instance not declared as public, please set `public_instance: true` at your earliest convenience.

**Comment by CameronMunroe** [comment]
> [@CameronMunroe](https://github.com/CameronMunroe) Hey! Thanks for keeping your searxng instance well maintained over the years. Just to let you know that your instance not declared as public, please set `public_instance: true` at your earliest convenience.

Try now.

**Comment by return42** [comment]
@CameronMunroe you have to activate the [`image_proxy](https://docs.searxng.org/admin/settings/settings_server.html) / issue has been reported by one of your users on [reddit Searx](https://www.reddit.com/r/Searx/comments/1mwseki/when_is_broken_image_search_getting_fixed/)

<img width="1028" height="327" alt="Image" src="https://github.com/user-attachments/assets/ee2c98c1-0865-47f4-818d-bc7a9276fe5e" />

**Comment by vojkovic** [comment]
> Please retry now, looks like the server needed a reboot.

Looks good!

**Comment by CameronMunroe** [comment]
Because bots are ridiculous these days; I have had to add anubis infront of the service.

Let me know if it is causing any issues with being monitored.

**Comment by vojkovic** [comment]
Yes it causes issues - you need to limit it to the
- /search endpoint; AND
- Allow check.searx.space IPs to bypass it.

When I used anubis, I used this policy:

```
bots:
  - name: searx-space
    action: ALLOW
    remote_addresses: [
      "167.235.158.251/32",
      "2a01:04f8:1c1c:8fc2::/64"
    ]

  - name: generic-search-rule
    path_regex: ^/search.*$
    action: CHALLENGE
    challenge:
      difficulty: 2
      report_as: 2
```

**Comment by CameronMunroe** [comment]
Thank you, implemented.

Newer anubis requires the "algorithm: fast " or other field under challenge:
