### ISSUE TITLE
Add https://coppedge.info

### ISSUE THREAD

**Issue by curlyfry248** [searxng/searx-instances#265]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by ononoki1** [comment]
Your site uses cookie `Set-Cookie: MOZSESSIONID=xxxx; Path=/; Secure; HttpOnly`, which is not necessary. Can you explain why?

**Comment by unixfox** [comment]
As a reminder we do not allow any analytics whatsoever. If you add analytics on your instance it will be removed forever.

**Comment by curlyfry248** [comment]
> Your site uses cookie `Set-Cookie: MOZSESSIONID=xxxx; Path=/; Secure; HttpOnly`, which is not necessary. Can you explain why?

Was accidentally added from the mozzila web security guidelines. Apologies and is now removed.

**Comment by unixfox** [comment]
Btw your instance is returning 404 to searx.space server: https://searx.space. See tab `offline & error`

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by vojkovic** [comment]
@curlyfry248 Looks like your TLS certs are expired - https://github.com/searxng/searx-instances-uptime/issues/12530
