### ISSUE TITLE
Add https://suche.tromdienste.de

### ISSUE THREAD

**Issue by aarontrom** [searxng/searx-instances#27]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Comment

where do I have to insert the code generated from https://ssl-config.mozilla.org/ in order to get A+ TLS grade?

**Comment by unixfox** [comment]
Hi aaron, unfortunately we can't really help you with the ssl-config from mozilla but when using caddy you will have a A+ TLS grade on https://cryptcheck.fr/: https://cryptcheck.fr/https/suche.tromdienste.de

**Comment by return42** [comment]
Hi @aarontrom, your instances are broken .. we consider to drop it from the searx.space list / https://github.com/searxng/searx-instances/pull/331#issuecomment-1702507792

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by aarontrom** [comment]
@unixfox So I am really sorry that it took so long for me to reply. 
I enabled this option `public_server: true` and restarted the service. I hope everything works and please let me know if I should change something else.

**Comment by aarontrom** [comment]
When I enable that option, SearX doesn't work anymore and I get a 502 Bad Gateway. Since I don't have the time and ressources at the moment, it would be better if this instance would be removed!

**Comment by unixfox** [comment]
It is because you did not follow the tutorial completely.

Please see the "Per type of installation": https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761#per-type-of-installation

**Comment by unixfox** [comment]
instance removed in https://github.com/searxng/searx-instances/commit/498e4090c6735da13c6e6c911e76ed867886f711

feel free to request to have your instance added back when you have found a way to enable the parameter.
