### ISSUE TITLE
Add https://searx.kutay.dev

### ISSUE THREAD

**Issue by Kutaygb** [searxng/searx-instances#289]
### Requirements

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Comment

:heart:

**Comment by ononoki1** [comment]
Hi @Kutaygb, you are loading custom CSS and JS with 404 error (line 26: `<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css">`). If these assets are not expected, it's recommended to remove them.

Besides, your [CSP](https://observatory.mozilla.org/analyze/searx.kutay.dev) grade is not optimal. However, it can be ignored if you do not mind being ranked lower on searx.space. If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

**Comment by Kutaygb** [comment]
@ononoki1 Thank you for informing me about the error on the site, I have fixed it now you can add it

**Comment by Kutaygb** [comment]
Hello @unixfox 

Thank you for the information. I have never used IPv6 before, but I tried to configure it. My internet doesn't support IPv6, I tested it through a website, and it seems to be working.

![image](https://github.com/searxng/searx-instances/assets/49347102/bbe9aa30-46df-4fd8-8130-baa45f3cbc31)

**Comment by unixfox** [comment]
Thank you, can confirm it works great.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
@Kutaygb 

Last warning before we will have to remove your instance for not adding the parameter.

**Comment by unixfox** [comment]
> @unixfox Can we remove my instance ? I'll be closing it soon.

sure please create a new issue for asking that: https://github.com/searxng/searx-instances/issues/new/choose
