### ISSUE TITLE
Add https://opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searx-instances#292]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/paulgoio/searxng

**Comment by unixfox** [comment]
Note: instance was previously removed due to bad uptime: https://github.com/searxng/searx-instances/commit/0284c37b7ca8e9e3ebc2d259f9e93567836791e0

**Comment by extremelyonline** [comment]
I apologize for the bad uptime. It was due to an update and maintenance of the nginx reverse proxy. The issue has been resolved, and I will keep the instance running to the best of my abilities.

**Comment by extremelyonline** [comment]
Thank you. I'm currently having another problem on Cryptcheck.fr. It seems that Cryptcheck cannot reach my website.  (Other sites such as [this](https://tls.imirhil.fr/https/opnxng.com) work.) 

The error is as follows. May I ask if this may be a problem on my end? Thank you.

`Error during analysis: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure`

**Comment by unixfox** [comment]
> Thank you. I'm currently having another problem on [Cryptcheck.fr.](https://cryptcheck.fr/https/opnxng.com) It seems that Cryptcheck cannot reach my website. (Other sites such as [this one](https://tls.imirhil.fr/https/opnxng.com) work.)
> 
> The error is as follows. May I ask if this may be a problem on my end? Thank you.
> 
> `Error during analysis: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure`

That's very odd, maybe you could try to create an issue on the original project: https://github.com/aeris/cryptcheck/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc?

**Comment by extremelyonline** [comment]
Thank you @unixfox. I have fixed the issue now. The site should be A+ at both [Cryptcheck.fr](https://cryptcheck.fr/https/opnxng.com) and the [Observatory](https://observatory.mozilla.org/analyze/opnxng.com).

Would you please check and see if my site can be relisted? Thank you so much.
