### ISSUE TITLE
[WIP] Add https://searx.soundar.eu.org

### ISSUE THREAD

**Issue by FatGrizzly** [searxng/searx-instances#31]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

A+ TLS Grade
First Indian instance to be on the list :)

**Comment by unixfox** [comment]
Why the WIP tag? Is it work in progress?

**Comment by FatGrizzly** [comment]
Yeah, I will fix it up soon, for some reason morty bugged out

**Comment by unixfox** [comment]
Ok then reopen the instance when you are done.
