### ISSUE TITLE
Add https://search.modalogi.com

### ISSUE THREAD

**Issue by georg-mayer** [searxng/searx-instances#314]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

the instance was down/unreliable for a long time, now changed to searxNG and docker - it is stable now

**Comment by ononoki1** [comment]
Hi @georg-mayer, your [CSP](https://observatory.mozilla.org/analyze/search.modalogi.com) grade is not optimal. However, it can be ignored if you do not mind being ranked lower on searx.space. If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

**Comment by georg-mayer** [comment]
Hello @ononoki1! Thank you so much - I forgot to put the CSP (and other headers) it in again - the issue should be fixed now, the rating at the observatory is A+ again. Sorry for the inconvenience and thanks for the support!

**Comment by unixfox** [comment]
CSP is still invalid

**Comment by georg-mayer** [comment]
@unixfox i removed the CSP from the apache reverse-proxy settings now - the console doesn't throw an error anymore. Not sure if this is what you requested. If there is a CSP setting needed can you please point me to the related section in the documentation (I searched and found none). 

I hope the instance is good to be listed now.

**Comment by georg-mayer** [comment]
@unixfox - I read this, I put the related CSP into my configuration, it throws the error at the console. I now put a working version of the CSP into my apache2.conf, it works when I open the site (no console errors) but now observatory.mozialla.org seems to hang, at least it doesn't load my results or allows a rescan. I will try tomorrow again. 

In any case, I am fine to be listed with a bad CSP rating, so please, if you don't find any error, just put the site on the list. I will look at the CSP issue later, my understanding is that the instances list querys the observatory dynamically, i.e. if the rating gets better, the list will show it.

Sorry for the confusion and thanks for your kind help.

**Comment by georg-mayer** [comment]
@unixfox I looked deeper into this. My understanding is (also from checking other sites) that this CSP is ok:
```
Content-Security-Policy "upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/searxng/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com"    
```
So I put it in, the Observatory gives me a A+ rating.

But when I open my search.modalogi.com page, Firefox Console throws this warning:

```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). content-script.js:40:65
```

Still - everything works.

I checked a number of other searx/searxNG sites which are listed on the searx-instances and they all have same/similar CSP and throw the same warning.

I really don't want to bother you, I am just feeling a bit confused whether you regard the FF-console warning as an error. If so, then this error is the same for at least a number of other searx sites. 

Any hint on how to improve on this is welcome, but I understand you are not here to educate me on CSP-setting. I just try to work it out the right way.

Thanks and cheers,
Georg

**Comment by unixfox** [comment]
That's great that you are trying to validate that the CSP works.
On my side, after visiting your searxng instance with Firefox I see no errors in the console, and it seems like your CSP rules are correct:
![image](https://user-images.githubusercontent.com/4016501/230027760-abd1a84e-f050-4aed-a14a-eecb93b11935.png)

It could be that an extension in your browser is trying to load a script, hence why CSP is so important because the browser will only load the resources of the website. You can validate again by visiting your website in incognito mode or by starting Firefox without any extension.

I guess if @ononoki1 have no objection, we can add your instance.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by unixfox** [comment]
@georg-mayer Important step above! The deadline has already passed, if you do not conform we will have to remove your instance by the end of the year.
