### ISSUE TITLE
Add https://searx.kujonello.cf

### ISSUE THREAD

**Issue by kujonello79** [searxng/searx-instances#33]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not installed correctly, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.kujonello.cf/search?category_general=1&q=ok&pageno=1&time_range=None&language=fr&format=json

You should look into fixing them.

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by kujonello79** [comment]
Yea, It's fine, You can add my instance anyway.

**Comment by unixfox** [comment]
Please remove any analytics software or we will have to remove your instance from the public list.
![image](https://user-images.githubusercontent.com/4016501/178549293-37d6a969-71bb-4eb8-9c02-13e00d433d74.png)

Unknown resource `https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194` is loaded on all the pages.

**Comment by kuj0nell0** [comment]
> Please remove any analytics software or we will have to remove your instance from the public list. ![image](https://user-images.githubusercontent.com/4016501/178549293-37d6a969-71bb-4eb8-9c02-13e00d433d74.png)
> 
> Unknown resource `https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194` is loaded on all the pages.

Hi,

It's me - kujonello. I've lost access to my previous github account. This script was loaded by cloudflare proxy. I haven't noticed it until today. So, as I noticed, I've disabled that. I would be thankful, if it would be possible to my instance be visible again on public instances list.
