### ISSUE TITLE
Are eu.org domains allowed?

### ISSUE THREAD

**Issue by jdev082** [searxng/searx-instances#338]
My instance is hosted under **s.jdev.eu.org**, would this qualify?

eu.org domains are free domains but don't have any of the issues that freenom domains have. They never expire.

**Comment by unixfox** [comment]
No see the rule that is written here:

> It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.

https://github.com/searxng/searx-instances/blob/master/.github/ISSUE_TEMPLATE/add-instance.yaml

**Comment by jdev082** [comment]
What's wrong with free domains?

**Comment by unixfox** [comment]
https://github.com/searxng/searx-instances/discussions/225

**Comment by jdev082** [comment]
eu.org domains have none of the issues stated in #225

**Comment by unixfox** [comment]
Well eu.org domains still fall into this category:
```
Usually websites under a free TLD are ephemeral, short-lived, mainly because the owner of the website didn't want to spend any money to start with.
```

We thrive to have instances in the list that will stay alive for a very long time, so if you can't even spend some money from your own pocket, it's not already a good start.

On top of that, I just looked at your instance and it is breaking a second rule:

> I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.

**Comment by jdev082** [comment]
ok
