### ISSUE TITLE
Add https://searx.masultan.xyz/

### ISSUE THREAD

**Issue by Abdulee** [searxng/searx-instances#34]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Source code URL
I have not modified any source code.

**Comment by unixfox** [comment]
Can you serve searx from the root path and not from /searx?

**Comment by Abdulee** [comment]
Hmmm yes, originally was using the root domain with /searx but managed to get a wildcard ssl so i guess ill fix that .. Is that required to add my instance?

**Comment by Abdulee** [comment]
Updated now. Please check thanks :+1:

**Comment by unixfox** [comment]
> Hmmm yes, originally was using the root domain with /searx but managed to get a wildcard ssl so i guess ill fix that .. Is that required to add my instance?

It's not required by highly recommended for the end users.

**Comment by unixfox** [comment]
Your filtron rules are not installed correctly, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.masultan.xyz/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You should look into fixing them.

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by Abdulee** [comment]
Hi, check again I have enabled filtron and set the limit of 2 on json results..

**Comment by dalf** [comment]
Hi,
I can still make an unlimited number of request to the URL given by @unixfox

**Comment by unixfox** [comment]
Closing due to a lack of replies.
Please reopen once you have fixed the issue or if you don't want to fix it then please let us know.
