### ISSUE TITLE
Add https://search.lightinthedark.space

### ISSUE THREAD

**Issue by ChillyKitty** [searxng/searx-instances#357]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Comment

Private search engine in Iceland ;3

**Comment by ChillyKitty** [comment]
I do have bot protection configured and added check.searx.space to the pass list in limiter.toml

**Comment by ononoki1** [comment]
Hi @ChillyKitty, your [CSP](https://observatory.mozilla.org/analyze/search.lightinthedark.space) grade is not optimal. However, it can be ignored if you do not mind being ranked lower on searx.space. If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

Besides, your instance seems to have an onion entry (http://uovv62vareccx6lw5c5ejbaox626ho3lab32htsx44dmf7x6zp2dusad.onion) that is broken now. Maybe you can fix that or remove the `Onion-Location` header on the clearnet?

**Comment by ChillyKitty** [comment]
CSP [should be good now](https://securityheaders.com/?q=https%3A%2F%2Fsearch.lightinthedark.space%2F) still waiting on a Mozilla Observatory scanner instance. Onion-Location header removed for now.

**Comment by ChillyKitty** [comment]
Hey @ononoki1! Thanks for the prompt response. 
CSP [is now passing as A+.](https://observatory.mozilla.org/analyze/search.lightinthedark.space). Mozilla was complaining about [Subresource integrity](https://infosec.mozilla.org/guidelines/web_security#subresource-integrity for my searxng instance).

Turns out having `SEARXNG_HOSTNAME=https://search.lightinthedark.space` broke part of it. Removing the https:// to make it `SEARXNG_HOSTNAME=search.lightinthedark.space` fixed it.
