### ISSUE TITLE
Add https://searx.jaska.cc

### ISSUE THREAD

**Issue by jaska087** [searxng/searx-instances#367]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
@jaska087 please explain the reason why your instance was down for a long time.

**Comment by return42** [comment]
FYI: first instance was added by @Jaska8 / this instance is added by @jaska087 / same identity?

**Comment by jaska087** [comment]
Due hardware failure i lost the instance and forgot about this project. Spun it back up recently.

Same reason for new account. Lost access to my 2fa and email, could not recove the github account

**Comment by unixfox** [comment]
We thrive to keep a list with instances that will stay up to date and available for a very long time.
@jaska087 how can you prove that you won't let down your instance again a second time? Do you have any monitoring system?

**Comment by jaska087** [comment]
It will be always up if the power/internet does not go down (probably 1-3 incidents a year) or the hardware does not blow up, again.

I have plans for future to build a cluster for redundancy, but not just yet.

**Comment by jaska087** [comment]
> Small notice:
> 
> for some reason our uptime checker can't check your instance or something is wrong with your webserver because your instance is reported down on it: [searxng/searx-instances-uptime#2865](https://github.com/searxng/searx-instances-uptime/issues/2865)

Yes, I'm middle of DNS propagation for my name servers so the domain has not authorative name servers.

You may change this instance add as resolved, I will be back once I get everything set up correctly.

**Comment by unixfox** [comment]
After one week your instance have 78% of uptime while we require 95% for being added back after it got removed once. As per explained in https://github.com/searxng/searx-instances#add-a-previously-submitted-instance

I'm sorry your instance does not qualify for being added back to the list.

I'm going to close your request but feel free to request again in a month, after your instance has stabilized.
