### ISSUE TITLE
Add https://search.xcloud.live

### ISSUE THREAD

**Issue by techcow2** [searxng/searx-instances#368]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by techcow2** [comment]
Please note - I will be resetting my server and installing a different version of Ubuntu so it utilizes less RAM. Due to this, my instance will be down for about a half hour today (8:30 PM EST - 9:00 PM EST).

Thank you.

**Comment by techcow2** [comment]
Trying to be proactive with this process...

I'm going to need some help setting up limiter. Initially, I had assumed docker took care of this as it's enabled in my settings.yml file by default. However, I see many bot requests on the syslog and auth.log. I've gone through the documentation here (https://docs.searxng.org/src/searx.botdetection.html#id5) and please forgive my ignorance. I still don't understand how to properly set up limiter. I'm still learning servers and Linux and I am quite a beginner. From what I understand, I'll need to create a limiter text file and add specific commands/parameters to the file. I know I'm also supposed to add to the settings.yml file, but I'm not exactly sure what to add and the correct way to do it.

This is supposed to be a fun project for me that I plan on maintaining and taking seriously. Hopefully, those with more knowledge than me can provide some easier-to-understand learning material than what I've found. I've gotten this far, so I don't think it's over my head, I just need someone to get me started in the right direction.

Thank you.

**Comment by unixfox** [comment]
How did you install searxng? The limiter does not block all the bots (yet).

**Comment by techcow2** [comment]
> How did you install searxng? The limiter does not block all the bots (yet).

Thanks for the quick reply! I installed searxng using docker/docker-compose on my VPS. (git clone https://github.com/searxng/searxng-docker.git).

**Comment by techcow2** [comment]
I would like to add that I see this error repeating in the Searxng logs (docker-compose logs -f) " 2023-07-18 15:10:20,892 ERROR:searx.botdetection: X-Real-IP header is not set!" I'm not sure if this is normal or if I need to act on this.

Thanks!

**Comment by unixfox** [comment]
You did not touch anything right? You did not change the "principal" webserver?

**Comment by techcow2** [comment]
> You did not touch anything right? You did not change the "principal" webserver?

I did not change the "principal" webserver. (I wouldn't know how). I didn't change anything besides adding moderate safe search, default autocomplete as DuckDuckGo, and switching from pull to GET requests all in the settings.yaml file which I will paste below. I also turned on ufw to allow ports and also iptables with the commands below:

ufw and iptable changes:
```
sudo iptables -I INPUT -m state --state NEW -p tcp --dport 80 -j ACCEPT
sudo iptables -I INPUT -m state --state NEW -p tcp --dport 443 -j ACCEPT
sudo ufw allow 80
sudo ufw allow 443
```
Here is my settings.yaml file:

```
# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "REDACTED FOR THIS POST"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
general:
  debug: false
  instance_name: "PrivCrawler.com - Private Search"
  contact_url: false
  enable_metrics: true
search:
  safe_search: 1
  autocomplete: "duckduckgo"
```
Sorry if this information is irrelevant, just trying my best to be as detailed as possible.

**Comment by unixfox** [comment]
You should be good to go then, everything is fine.

Again the limiter can't block all the bots yet.

This may change in the future: https://github.com/searxng/searxng/pull/2357

**Comment by techcow2** [comment]
> You should be good to go then, everything is fine.
> 
> Again the limiter can't block all the bots yet.
> 
> This may change in the future: [searxng/searxng#2357](https://github.com/searxng/searxng/pull/2357)

Great! Thanks for confirming that.

**Comment by unixfox** [comment]
please don't reopen another one, just give us the new domain here and we will edit the issue.
