### ISSUE TITLE
Edit https://myprivatesrx.us

### ISSUE THREAD

**Issue by hmcclurg** [searxng/searx-instances#376]
Instance added by the issue #286

Please change my instance domain from myprivatesrx.us to searxng.online

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by hmcclurg** [comment]
@unixfox  - I must have missed your comment and noticed that my instance is no longer on searx.space - I enabled the parameter and was wondering if my instance could be re-added. Apologies for the inconvenience.

**Comment by unixfox** [comment]
> @unixfox  - I must have missed your comment and noticed that my instance is no longer on searx.space - I enabled the parameter and was wondering if my instance could be re-added. Apologies for the inconvenience.

Please create a new github issue for asking to get your instance added back. Thank you
