### ISSUE TITLE
Add https://searx.zhenyapav.com

### ISSUE THREAD

**Issue by ZhenyaPav** [searxng/searx-instances#378]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by ononoki1** [comment]
Hi @ZhenyaPav, your [TLS](https://cryptcheck.fr/https/searx.zhenyapav.com) and [CSP](https://observatory.mozilla.org/analyze/searx.zhenyapav.com) grades are not optimal. However, these grades can be ignored if you do not mind being ranked lower on searx.space. If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

**Comment by ZhenyaPav** [comment]
Thank you for the heads-up @ononoki1, I've fixed the issues. You can add my instance now.

**Comment by unixfox** [comment]
hello @ZhenyaPav , make sure to keep your instance up to date. your instance needs to be at the very least 1 week old, it's 2 months old!

when there will be a second warning, your instance will be removed.

**Comment by ZhenyaPav** [comment]
> hello @ZhenyaPav , make sure to keep your instance up to date. your instance needs to be at the very least 1 week old, it's 2 months old!
> 
> when there will be a second warning, your instance will be removed.

Just updated the instance

**Comment by Aadniz** [comment]
@ZhenyaPav  Saving settings in the preferences redirects to https://localhost

Similar issues can also be found here https://searx.zhenyapav.com/info/en/about, many links redirect to https://localhost/stats, https://localhost/preferences etc

**Comment by ZhenyaPav** [comment]
> [@ZhenyaPav](https://github.com/ZhenyaPav) Your instance has been down for over two weeks - [searxng/searx-instances-uptime#10193](https://github.com/searxng/searx-instances-uptime/issues/10193)
> 
> Can you please work to address this so we don't need to remove your instance from the list? Thanks

Hello, unfortunately I no longer use SearXNG myself, and do not have the time or reason to maintain the VPS it was hosted on. I think it would be best if my instance is removed from the list. Should I re-setup it I'm the future, I will apply again, but right now I do not have such plans
