### ISSUE TITLE
Add https://searx.milesy.tech

### ISSUE THREAD

**Issue by sumiles** [searxng/searx-instances#38]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by tiekoetter** [comment]
Your instance includes JS from static.cloudflareinsights.com and loads the rocket-loader.js. This will decrease your HTTP grade on searx.space.
Do you really need Cloudflare in front of your instance?

Also check [observatory.mozilla.org](https://observatory.mozilla.org/analyze/searx.milesy.tech) for additional header advice.

**Comment by unixfox** [comment]
Closing due to a lack of replies.
Please reopen after replying to the question of tiekoetter
