### ISSUE TITLE
Add https://freesearch.club

### ISSUE THREAD

**Issue by knikolaeff** [searxng/searx-instances#380]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), Cloudflare, shared Web hosting. TCP load balancer is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

I have previously added this instance, but it was removed due to downtime. I have resolved the issues and now my instance is on 24/7. Thank you for your understanding.

**Comment by unixfox** [comment]
@knikolaeff could you give us a reason why your instance went down in May a couple of days after your asked to be added to the list?

**Comment by knikolaeff** [comment]
@unixfox I am indeed the owner. The username is the same here #304. I went abroad and my server has gone down for some reason. There were no notifications so I only found out about it because my friend told me. I am setting up a notifications system on my host to react quicker if that happens again. The system does not collect any personal information and monitors the server's status only.

**Comment by unixfox** [comment]
Thank you for your reply.

I see one big issue is that you don't update your instance often enough, during 2 months there have been many new changes to searxng. One way to keep it up to date is to use watchtower.

Did you setup an external monitoring system or one that is only hosted on your server? If it's the latter one you won't be notified if your server is down.

**Comment by knikolaeff** [comment]
Thank you for pointing me in the right direction. I have successfully installed the watchtower. 
![image](https://github.com/searxng/searx-instances/assets/80189148/9830b339-9bea-4849-a740-bca5d73c97b9)

The monitoring system is external and will notify me if my server is down via email.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.
