### ISSUE TITLE
Delete search.xcloud.live

### ISSUE THREAD

**Issue by techcow2** [searxng/searx-instances#387]
My instance is no longer working with Google and duckduckgo so I'm giving up. I tried everything and it looks like there's no solution. Not sure what happened, everything was working fine until now.

You can delete search.xcloud.live as it will be permanently shut down today.

**Comment by return42** [comment]
Did you read [my comment](https://github.com/searxng/searxng/issues/2649#issuecomment-1680128328)

> Use your instance IP as a proxy for your WEB browser to see whats going on .. / see https://docs.searxng.org/admin/answer-captcha.html

**Comment by unixfox** [comment]
remove in https://github.com/searxng/searx-instances/commit/bec24a8fbef846f5095774eab7581d3292551942
