### ISSUE TITLE
Add https://nyc1.sx.ggtyler.dev

### ISSUE THREAD

**Issue by ggtylerr** [searxng/searx-instances#406]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

Main node is at NYC hosted at https://nyc1.sx.ggtyler.dev (the URL in the issue title redirects to this to prevent any confusion in the software and/or user.) Also hosted on Seattle and Paris on the `sea1` and `par1` subdomains. Future nodes will use this same naming convention.

Setup is on Docker Compose using [this slightly modified setup](https://github.com/searxng/searxng-docker/discussions/156#discussioncomment-6220808) to use nginx. IPs will be monitored and banned manually, and if needed, I'll add crowdsec to all my servers as additional protection.

**Comment by unixfox** [comment]
Hi, there is a new requirement for new public instances please see: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

Also I can invite you to a matrix room for only public instances maintainers, we discuss new changes and share advice on managing an instance.   
Do you want to get added?

**Comment by ggtylerr** [comment]
Added that option to all nodes. Please invite, user is ggtyler:matrix.org

**Comment by ononoki1** [comment]
Hi @ggtylerr, your instance seems to use an HTTP load balancer by GCP to redirect requests to subdomains (from **sx.ggtyler.dev** to **nyc1.sx.ggtyler.dev**). This violates the rule below.

> I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, _**managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB)**_, shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.

**Comment by ggtylerr** [comment]
> Hi @ggtylerr, your instance seems to use an HTTP load balancer by GCP to redirect requests to subdomains (from **sx.ggtyler.dev** to **nyc1.sx.ggtyler.dev**). This violates the rule below.
> 
> > I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, _**managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB)**_, shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.

Are you kidding me? It's a DNS redirect. You can even see it if you do a DNS record lookup. Just add nyc1.sx.ggtyler.dev if it's that violating.

**Comment by ononoki1** [comment]
Requests to **sx.ggtyler.dev** are handled by Google Host Server (ghs), not your server.

```
$ curl -I sx.ggtyler.dev
HTTP/1.1 302 Found
Location: https://nyc1.sx.ggtyler.dev/
Date: Sun, 01 Oct 2023 15:27:09 GMT
Content-Type: text/html; charset=UTF-8
Server: ghs
Content-Length: 225
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
```

> Just add nyc1.sx.ggtyler.dev if it's that violating.

I'll change the title to `Add https://nyc1.sx.ggtyler.dev` and reopen this issue.
