### ISSUE TITLE
Add https://searx.misoni.me

### ISSUE THREAD

**Issue by misonln41** [searxng/searx-instances#41]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (other rules).

**Comment by tiekoetter** [comment]
Your instance is using Cloudflare. Please note that this will negatively reflect in the instances list.
The headers are also not optimal (https://observatory.mozilla.org/analyze/searx.misoni.me). This will decrease your CSP grade.

**Comment by tiekoetter** [comment]
ping @misonln41

**Comment by misonln41** [comment]
I'm sorry for my slow reply. 
I understood that my instance has nonoptimal hearts and using Cloudflare is not recommended. I want to fix these problems as soon as possible, but now I don't have enough time to do.
It's okay not to add my instance right now. When I have fixed my instance, I will re-open issue.
