### ISSUE TITLE
Delete https://spot.murena.io

### ISSUE THREAD

**Issue by nfk** [searxng/searx-instances#413]
Please remove our instance from searx.space. It is hard for us to handle the whole traffic and providing a good experience for our users. You can confirm my identity from [there](https://gitlab.e.foundation/e/infra/spot/-/project_members).

Instance added by the issue #211

**Comment by unixfox** [comment]
Hello,

Removing your instance from the list will never make the bots go away. Your instance is too well known by the public and well indexed in various search engines.

We recommend enabling our built-in rate limiter which you can easily do by following this tutorial: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

Even if you are running a public instance anymore to the eyes of our public list, this parameter allow to benefit from the protections designed for searxng instances that are exposed to the public.

Our built-in protections will not make all the bots go away but they will greatly reduce them.

**Comment by nfk** [comment]
@unixfox Thank you for your advices! We are working on it to limit bots usage.
