### ISSUE TITLE
https://sea.gr3n.de

### ISSUE THREAD

**Issue by gruenheit** [searxng/searx-instances#42]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by tiekoetter** [comment]
Your instance uses Cloudflare. Note that this will be shown on searx.space. Please consider to disable Cloudflare's reverse proxy for your instance.
Your instance also doesn't have a good selection of headers (https://observatory.mozilla.org/analyze/sea.gr3n.de). This will decrease your CSP grade on searx.space.
