### ISSUE TITLE
Add https://search.2-a.net

### ISSUE THREAD

**Issue by hzm170** [searxng/searx-instances#421]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

**Comment by unixfox** [comment]
Please configure the parameter `server.public_instance`: https://github.com/searxng/searx-instances/discussions/417

**Comment by hzm170** [comment]
> Please configure the parameter `server.public_instance`: #417

i did how ever it's crashing the system and everything is config right.. is there bug or file missing from it?

**Comment by unixfox** [comment]
what do you mean by crashing the system? the whole system? or just searxng?

check your logs...

**Comment by hzm170** [comment]
> what do you mean by crashing the system? the whole system? or just searxng?
> 
> check your logs...

it's crashing the docker system, from what the logs says 

`Respawned uWSGI worker 4 (new pid: 229)
spawned 4 offload threads for uWSGI worker 7
spawned 4 offload threads for uWSGI worker 3
spawned 4 offload threads for uWSGI worker 4
2023-10-17 18:21:55,549 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the bot limiter and link_token plugins.
2023-10-17 18:21:55,564 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the bot limiter and link_token plugins.
2023-10-17 18:21:56,800 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the bot limiter and link_token plugins.
2023-10-17 18:21:56,841 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the bot limiter and link_token plugins.
2023-10-17 18:21:56,851 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the bot limiter and link_token plugins.`

**Comment by unixfox** [comment]
please explain how you installed searxng

**Comment by hzm170** [comment]
ah yes, i use it for DNS from RProxy due to i don't get static IP here yet.. but u can close this out i will try again soon with a static

**Comment by unixfox** [comment]
Ask for a reopen of this issue once:

- You have removed cloudflare
- You have `public_instance` parameter enabled.
