### ISSUE TITLE
Add https://search.inetol.net

### ISSUE THREAD

**Issue by Inetol** [searxng/searx-instances#424]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

### Source code URL

https://github.com/Inetol/container-searxng

### Comment

Previously, I requested the removal (#372) due to issues with bots, now I'm more confident that this won't be a problem anymore and therefore I reapply

**Comment by Inetol** [comment]
@ononoki1 It's been a week already ;)

**Comment by return42** [comment]
@inetol there is `secunet-cgi/send-challenge` ..

https://search.inetol.net/secunet-cgi/send-challenge?result=6d302601788185d9eef3e8d5b217c743658fca8edbaac59e53d5e7877ac2af83&nonce=0&origin=https://search.inetol.net/search?q=foo

and a `X-Substation-SecuNET-Visa=...` cookie when I visit your instance.

I know you are familiar with the requirements around privacy ... can you please briefly explain what the cookie (and the `secunet-cgi/send-challenge`) are needed for and whether it might be possible to identify the user? .. Thank you!

**Comment by inetol** [comment]
Sure, the cookie contains hashed information to allow access to protected routes where this solution is deployed (in this case "/search"), It has info about the challenge result, its type and client/gateway information such as User-Agent header. Then the cookie is signed with an internal certificate and stored to the client if it's allowed to proceed. The cookie means nothing to anyone but the gateway to identify between good and bad actors, it is unique and immutable (until the cookie itself expires, client information changes or the internal certificate rotates) and the hash cannot be reversed, obviously.

As this was added as an experiment there is no cookie policy or anything yet, its yet too early to define exactly how the cookie will be used, but that is its initial purpose. If there are still any privacy concerns, I can revoke the experiment for the site.

**Comment by return42** [comment]
>  If there are still any privacy concerns, I can revoke the experiment for the site.

Not from my side .. I had already thought of something similar and was just inquisitive .. may you came back one day and report your experience to the SearXNG project 👍
