### ISSUE TITLE
Edit https://search.inetol.net

### ISSUE THREAD

**Issue by Inetol** [searxng/searx-instances#432]
Instance added by the issue #424 

The OÑO address is now available: [searchpie7fejn4wctzm6fgm6oz5vnziltfzzuec6b4qmkr3wrqaoqqd.onion](http://searchpie7fejn4wctzm6fgm6oz5vnziltfzzuec6b4qmkr3wrqaoqqd.onion)

**Comment by unixfox** [comment]
@inetol your onion service is down: http://searchpie7fejn4wctzm6fgm6oz5vnziltfzzuec6b4qmkr3wrqaoqqd.onion/

**Comment by inetol** [comment]
Should be fixed by now
