### ISSUE TITLE
Add https://etsi.me

### ISSUE THREAD

**Issue by animegrafmays** [searxng/searx-instances#45]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Source code URL

https://git.poast.org/etsi/etsi.me

**Comment by tiekoetter** [comment]
Your instance uses a modified version of SearXNG but you don't publish the source code. Please publish the modified source code.

The headers are not optimal (https://observatory.mozilla.org/analyze/etsi.me).
Please fix `-dirty` (in the footer of your instance) this happens when you have uncommitted changes (likely your changed image)

**Comment by animegrafmays** [comment]
this has been resolved including headers

**Comment by tiekoetter** [comment]
The source code URL is not valid.
<img width="831" alt="Bildschirmfoto 2022-04-16 um 02 35 29" src="https://user-images.githubusercontent.com/77782671/163654961-631729f4-5263-4830-846a-2fb6f36321b7.png">
Your CSP header will block embedded videos for example.

The CSP header my instance uses:
``add_header Content-Security-Policy "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/tiekoetter/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src 'self' https://www.youtube-nocookie.com https://invidious.tiekoetter.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com https://open.spotify.com/" always;``

You also serve your instance from ``/searx`` but it is also accessible from ``/``. Please confirm if this is intended.

**Comment by animegrafmays** [comment]
I have adapted your CSP for use with our invidous and nitter and corrected the sourcecode issue.

every time I try to serve searxNG without using 
`    proxy_set_header   X-Script-Name    /searx;`
in nginx's configuration results in a rate limit error but this is something I will be addressing this week when I have time to figure it out

**Comment by tiekoetter** [comment]
You can remove ``proxy_set_header X-Script-Name /searx;``.
I would recommend switching to redis + limiter plugin (I use it and it works really well for me).

If you still want to use filtron you can use the filtron rules.json I used to use:
```[
    {
        "name": "roboagent limit",
        "filters": [
            "Header:User-Agent=(curl|cURL|Wget|python-requests|Scrapy|FeedFetcher|Go-http-client|Ruby|UniversalFeedParser)"
        ],
        "limit": 0,
        "stop": true,
        "actions": [
            { "name": "log"},
            { "name": "block",
              "params": {
                  "message": "Rate limit exceeded"
              }
            }
        ]
    },
    {
        "name": "botlimit",
        "filters": [
            "Header:User-Agent=(Googlebot|bingbot|Baiduspider|yacybot|YandexMobileBot|YandexBot|Yahoo! Slurp|MJ12bot|AhrefsBot|archive.org_bot|msnbot|MJ12bot|SeznamBot|linkdexbot|Netvibes|SMTBot|zgrab|James BOT)"
        ],
        "limit": 0,
        "stop": true,
        "actions": [
            { "name": "log"},
            { "name": "block",
              "params": {
                  "message": "Rate limit exceeded"
              }
            }
        ]
    },
    {
        "name": "suspiciously frequent IP",
        "filters": [],
        "interval": 600,
        "limit": 30,
        "aggregations": [
            "Header:X-Forwarded-For"
      ],
        "actions":[
            {"name":"log"}
      ]
    },
    {
        "name": "search request",
        "filters": [
            "Param:q",
            "Path=^(/|/search)$"
        ],
        "interval": 61,
        "limit": 999,
        "subrules": [
            {
                "name": "missing Accept-Language",
                "filters": ["!Header:Accept-Language"],
                "limit": 0,
                "stop": true,
                "actions": [
                    {"name":"log"},
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "suspiciously Connection=close header",
                "filters": ["Header:Connection=close"],
                "limit": 10,
                "stop": true,
                "actions": [
                    {"name":"log"},
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "IP limit",
                "interval": 61,
                "limit": 9,
                "stop": true,
                "aggregations": [
                    "Header:X-Forwarded-For"
                ],
                "actions": [
                    { "name": "log"},
                    { "name": "block",
                      "params": {
                          "message": "Rate limit exceeded"
                      }
                    }
                ]
            },
            {
                "name": "rss/json limit",
                "filters": [
                    "Param:format=(csv|json|rss)"
                ],
                "interval": 121,
                "limit": 2,
                "stop": true,
                "actions": [
                    { "name": "log"},
                    { "name": "block",
                      "params": {
                          "message": "Rate limit exceeded"
                      }
                    }
                ]
            },
            {
                "name": "useragent limit",
                "interval": 61,
                "limit": 199,
                "aggregations": [
                    "Header:User-Agent"
                ],
                "actions": [
                    { "name": "log"},
                    { "name": "block",
                      "params": {
                          "message": "Rate limit exceeded"
                      }
                    }
                ]
            }
        ]
    }
]
```

**Comment by animegrafmays** [comment]
cheers, the above rules worked -- thanks

I will be switching to redis as we deployed it for use with a large fediverse instance and it will benefit greatly from using redis

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by animegrafmays** [comment]
this has been done

**Comment by unixfox** [comment]
Your instance is outdated, please update it and keep it up to date.

**Comment by vojkovic** [comment]
@animegrafmays Your instance is outdated again, we have a lot of recent engine patches. It is recommended to setup an auto updater so you don't need to do this manually anymore :)

Current version: `2026.5.2+aefc3c316`

**Comment by animegrafmays** [comment]
Will manually update now, sorry -- recently with the C&D from X in regards to Nitter and our main fediverse instance falling victim to a CVE that mistakenly rolled back during patching I have been extremely busy. Will do my best to automate it in the coming weeks

**Comment by vojkovic** [comment]
All good, I understand you have your work cut out for you

Go get em' ❤️
