### ISSUE TITLE
Delete https://search.nadeko.net

### ISSUE THREAD

**Issue by Fijxu** [searxng/searx-instances#465]
Oracle deleted my account without any reason and the VPS where searxng was hosted was deleted too. For now, my SearxNG instance is now unavailable.

Instance added by the issue #25
Pull request at https://github.com/searxng/searx-instances/pull/464

More info at https://noc.social/@fijxu/111759998134217270

**Comment by unixfox** [comment]
You probably received an automated DMCA from Google. Oracle immediately removes your server once it receives a DMCA.

In the past I received a DMCA from Google at hetzner and that happened to multiple people on hetzner too.
