### ISSUE TITLE
Add https://search.privacyguides.net

### ISSUE THREAD

**Issue by jonaharagon** [searxng/searx-instances#47]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Comment

Doesn't _technically_ use filtron, it uses the limiter plugin added in https://github.com/searxng/searxng-docker/pull/12, maybe your issue template should be updated?

**Comment by jonaharagon** [comment]
@tiekoetter oop, I literally *just* updated it. Should be good.

**Comment by unixfox** [comment]
> You could consider to use a 384 bit certificate and diffie hellman. [tls.imirhil.fr/https/search.privacyguides.net](https://tls.imirhil.fr/https/search.privacyguides.net)
> 
> Everything else looks good. Just confirm if I should add the instance now or if you want to do some changes first.

Everything looks great on the new tool (tls.imirhil.fr is deprecated): https://cryptcheck.fr/https/search.privacyguides.net
