### ISSUE TITLE
Remove http://privateoz3u5utrimal2edr56j3r5caakektxxgixigdkycuxigvquid.onion

### ISSUE THREAD

**Issue by vojkovic** [searxng/searx-instances#489]
Remove privateoz3u5utrimal2edr56j3r5caakektxxgixigdkycuxigvquid.onion as a link for priv.au.

It's simply too difficult for me to continue to implement any bot protection for my onion site whilst retaining its functionality for human users.

Instance added by the issue https://github.com/searxng/searx-instances/issues/185

**Comment by return42** [comment]
> It's simply too difficult for me to continue to implement any bot protection for my onion site whilst retaining its functionality for human users.

@vojkovic I'm not sure its related to your comment from above: when I visit https://priv.au/ I can read in the footer ..

![Image](https://github.com/user-attachments/assets/4dbcf1f4-9067-49b5-90e2-0caca74358c7)

Is this a currently existing problem? ... is there a suitable issue on https://github.com/searxng/searxng ... or is this just a forgotten remnant from 2024?

**Comment by vojkovic** [comment]
@return42

I've been looking at a custom l7 bot protection for priv.au as one of the larger SearXNG instances, the default botdetection is still enabled.

The message provided was related to a report of it failing for a user with JShelter enabled so it was disabled while I work on a fix. I should say that any botdetection I deploy should work for all of my users (no-js incl).

**Comment by return42** [comment]
> I've been looking at a custom l7 bot protection for priv.au 

Aah, nice .. when you are ready I would like to hear more about your experiences .. 🚀
