### ISSUE TITLE
Add https://searx.bardia.tech

### ISSUE THREAD

**Issue by BardiaMGTGC** [searxng/searx-instances#50]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by tiekoetter** [comment]
Hi @BardiaMGTGC,
We stoped accepting Instances which are based on [searx/searx](https://github.com/searx/searx).

Please update your instance so that it uses either [searxng/searxng](https://github.com/searxng/searxng) or a fork of it.

If you need help switching from SearX to SearXNG you can consult this [guide](https://docs.searxng.org/admin/installation-switch2ng.html) or ask for help here.

**Comment by BardiaMGTGC** [comment]
Done

**Comment by tiekoetter** [comment]
Your [headers](https://observatory.mozilla.org/analyze/searx.bardia.tech) and [TLS](https://cryptcheck.fr/https/searx.bardia.tech) configuration are not optimal.

Your instance can be added anyway you will just be ranked lower (just write another comment confirming this and I will add the instance).

**Comment by BardiaMGTGC** [comment]
It seems fine here
https://www.ssllabs.com/ssltest/analyze.html?d=searx.bardia.tech
https://www.ssllabs.com/ssltest/analyze.html?d=bardia.tech

I have never seen any of those TLS tests in my life but our configuration seems fine to us

**Comment by tiekoetter** [comment]
> I have never seen any of those TLS tests in my life but our configuration seems fine to us

This is the test which is used by searx.space.

On ssllabs it reports them as well.

`TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 `
`TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 `

I will add your instance now.

**Comment by unixfox** [comment]
Again down: https://github.com/searxng/searx-instances-uptime/issues/312

Watchout we will remove your instance if it goes below 90% of uptime which is roughly 3 days of downtime in a month.
