### ISSUE TITLE
Add https://find.mordorgates.xyz

### ISSUE THREAD

**Issue by drm-gith** [searxng/searx-instances#502]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

**Comment by drm-gith** [comment]
When i make the  server.public_instance parameter true, i lost acess. I need to rebulid. Can you help me ?

**Comment by drm-gith** [comment]
I tried, still down even with server.limiter=true + server.public_instance=true. 
I`m use this on docker, with a external nginx, and the route is ok, but when activate the server.public on yml, lost acess.

**Comment by unixfox** [comment]
Please read the tutorial: https://github.com/searxng/searx-instances/discussions/417

**Comment by drm-gith** [comment]
I read, and do the folowing: 
searxng-docker already have both the limiter and redis activated it's a simple change for you.

    Go to the directory of searxng-docker
    Update the directory by pulling the latest changes: git pull
    Edit the file settings.yml.
    Add the line public_instance: true in the section server:. Example:

server:
  public_instance: true

    Update SearXNG and restart it

docker-compose pull
docker-compose up -d
docker-compose restart
.

Also add redis on my docker compose 

services:
  redis:
    image: redis:alpine
    
and add the url on settings, like this:
redis:
  url: redis://localhost:6379/1

but still lose acess when enable public_instance, and recover is i set as false.

**Comment by unixfox** [comment]
What do you mean by "loose access"?

Please be more descriptive of the issue.

**Comment by ononoki1** [comment]
Close due to lack of reply.
