### ISSUE TITLE
Add https://searx.hu

### ISSUE THREAD

**Issue by skidoodle** [searxng/searx-instances#504]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

**Comment by vojkovic** [comment]
> @maintainers Warning, instance found in the commit history, make sure to wait 1 week before adding the instance if needed. See here for more information: https://github.com/searxng/searx-instances#add-a-previously-submitted-instance
> 
> ```
> Commit ID: 99a45d4d0676691503d869d798e71b6e112761a5
>  - Date: Tue Feb 15 14:31:35 2022 +0000
>  - Description: Delete https://searx.hummel-web.at
>  - Author: Émilien Devos
> 
> Commit ID: ee81ae3d11946efa3dd4423faeb846d5b23b09a1
>  - Date: Tue Sep 14 18:48:36 2021 +0200
>  - Description: Add https://searx.hummel-web.at
>  - Author: Emilien Devos
> ```

Looks like a different instance got flagged here. @unixfox

**Comment by ononoki1** [comment]
The IPv6 address (2a09:7ac0:0:0:0:1:e11b:96ab) of your instance is inaccessible.

**Comment by skidoodle** [comment]
> The IPv6 address (2a09:7ac0:0:0:0:1:e11b:96ab) of your instance is inaccessible.

https://github.com/searxng/searxng-docker/issues/183

**Comment by unixfox** [comment]
> > The IPv6 address (2a09:7ac0:0:0:0:1:e11b:96ab) of your instance is inaccessible.
> 
> https://github.com/searxng/searxng-docker/issues/183

No ipv6 works with searxng-docker. The issue is about using default ipv6 in docker.

Because currently we use host network for the webserver

**Comment by skidoodle** [comment]
I'm happy to report that the IPv6 connectivity issue has been resolved!

It turned out the problem originated with my previous hosting provider's IPv6 gateway. I've migrated my instance to a new provider with functioning IPv6 support, and everything seems to be working smoothly now.
