### ISSUE TITLE
Add https://search.indst.eu

### ISSUE THREAD

**Issue by NicoloLazzaroni** [searxng/searx-instances#508]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

**Comment by NicoloLazzaroni** [comment]
Added TOR alias: http://whereissky27lxfdrs7ct7a5ievor3tl67qi77rv5luga7wod5jf2mad.onion/

**Comment by ononoki1** [comment]
You are redirecting https://search.indst.eu/ to https://search.indst.eu/searxng/. It's OK, but we recommend directly use the root path for SearXNG instead of adding a subpath.

**Comment by NicoloLazzaroni** [comment]
> You are redirecting https://search.indst.eu/ to https://search.indst.eu/searxng/. It's OK, but we recommend directly use the root path for SearXNG instead of adding a subpath.

I'll keep it that way for now, way too many devices set to use that subpath, thank you.

**Comment by ononoki1** [comment]
You seem to use tracking service from iubenda, which violates your promise here:

> I do not track the users of my instance with any analytics or tracking software.

Please remove it for your instance to be added.

**Comment by unixfox** [comment]
Also means that you must disclose the source code of your instance since it is not running a vanilla code anymore.

As per the AGPL license conditions.

**Comment by NicoloLazzaroni** [comment]
I don’t? As said the JS has been removed.
I only have modified the HTML of the footer and the navbar, but I have everything else vanilla.

I am not the only one and as I update automatically through docker, it would be problematic to update the source code every time I update the software (which happens twice a week or more).

> > The external JS code was used for cookie approval and policy, not tracking. After a discussion about its use on Matrix it has been removed and SearXNG reset to default.
> 
> You have a modified version of SearXNG, see [#508 (comment)](https://github.com/searxng/searx-instances/issues/508#issuecomment-2083163945) ..
> 
> > Also means that you must disclose the source code of your instance since it is not running a vanilla code anymore.
> > In this issue and in the footer of the instance.
> > As per the AGPL license conditions.

**Comment by return42** [comment]
Thanks 👍 .. 

> Download the files in this repo and replace the ones present in the lastest version of [SearXNG](https://github.com/searxng/searxng).

If you just copy the file you will lost modifications of the (e.g.) `base.html` from upstream SearXNG and its hard for you to see if there is an typo .. 

Therefore its recommended to create a branch and apply your patches on the branch, such a running branch (we call it a "brand") has its setup here:

- https://docs.searxng.org/admin/settings/settings_brand.html 

If you do so, you can better track conflicts and typos .. here is one typo I can see in you `base.html` (`center-aligment-` vs `center-alignment-`) ..

```diff
modified   searx/templates/simple/base.html
@@ -1,7 +1,7 @@
 <!DOCTYPE html>
-<html class="no-js theme-{{ preferences.get_value('simple_style') or 'auto' }} center-alignment-{{ preferences.get_value('center_alignment') and 'yes' or 'no' }}" lang="{{ locale_rfc5646 }}" {% if rtl %} dir="rtl"{% endif %}>
+<html class="no-js theme-{{ preferences.get_value('simple_style') or 'auto' }} center-aligment-{{ preferences.get_value('center_alignment') and 'yes' or 'no' }}" lang="{{ locale_rfc5646 }}" {% if rtl %} dir="rtl"{% endif %}>
```

-------------

Here by example is my `darmarit.org` branch I use for my instance on https://darmarit.org/searx/

- https://github.com/return42/searxng/tree/darmarit.org

To "update" the branch (`origin`is my fork), I do a git rebase on `upstream` master (SearXNG):

```
$ git checkout -b darmarit.org origin/darmarit.org
$ git rebase --autostash upstream/master
$ git push -v --force-with-lease origin
```

**Comment by return42** [comment]
> However, as I only have the base.html file modified, having the full code to manually update is not worth the benefits.

As you prefer .. but have in mind; `base.html` will change one day / silently if you don't track.
