### ISSUE TITLE
Add https://search.nerdvpn.de

### ISSUE THREAD

**Issue by Sommerwiesel** [searxng/searx-instances#511]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

### Comment

Site accessibility test: [uptrends.com](https://www.uptrends.com/tools/uptime?toolRequestGuid=bad99782-2ec4-4723-91a5-7743f7882c6b)

I also use basic, light bot protection in nginx and have made sure that uptime checks such as those coming from check.searx.space are whitelisted. The bot protections have never caused any issues for my other public services.

**Comment by return42** [comment]
@Sommerwiesel You can update your SearXNG instance without switching to Valkey first.

Currently, the Valkey and Redis APIs are still compatible, but this will silently change at some day (we don't know), which is why we recommend switching to Valkey.

If you have set up the Redis instance with the SearXNG scripts, then the switch is relatively easy:

1. [remove Redis instance](https://docs.searxng.org/admin/settings/settings_redis.htmL)
2. [install Valkey](https://docs.searxng.org/admin/settings/settings_valkey.html#valkey-developer-notes)

**Comment by return42** [comment]
> Honestly, I hate the whole redis vs valkey situation...

Yeah [*The migration to valkey is necessary because the company behind Redis has decided to abandon the open source license ...*](https://github.com/searxng/searxng/discussions/4986)

> Have just manually updated my instance to 10.28 fyi

*kewl* 👍
