### ISSUE TITLE
Add https://search.kvj.ovh

### ISSUE THREAD

**Issue by kuj0nell0** [searxng/searx-instances#515]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

### Comment

using docker: searxng/searxng:latest

**Comment by ononoki1** [comment]
Hi @kuj0nell0, your [TLS](https://cryptcheck.fr/https/search.kvj.ovh) grade is only **F**. Please at least get an **E** grade for your instance to be added.

**Comment by unixfox** [comment]
Closing due to lack of replies.

**Comment by unixfox** [comment]
You need to have better letter than F on cryptcheck or your instance can't be added sorry.

A B on ssllabs seems to indicate a bad TLS security.

**Comment by kuj0nell0** [comment]
Managed to get A on [sslabs](https://www.ssllabs.com/ssltest/analyze.html?d=search.kvj.ovh).

**Comment by kuj0nell0** [comment]
> You need to have better letter than F on cryptcheck or your instance can't be added sorry.
> 
> B on ssllabs seems to indicate a bad TLS security.

will try at 22:46:41 UTC it seems
![20240518_00h35m08s_grim](https://github.com/searxng/searx-instances/assets/106756149/add40e88-21de-4e06-9e00-ef211d481d4e)

**Comment by kuj0nell0** [comment]
@unixfox got[ A+ ](https://cryptcheck.fr/https/search.kvj.ovh)

**Comment by unixfox** [comment]
Ok great, for me your TLS configuration seems to be a bit too harsh now.

See mine: https://cryptcheck.fr/https/searx.be

Like android 6, IE11 on windows 10 and early versions of Edge won't be able to load your instance.

https://ssl-config.mozilla.org/ is a good starting point for a good ssl configuration. I meant starting point because you won't get an A+ directly, you need to tweak a little bit more.
