### ISSUE TITLE
Add https://search.roombob.cat

### ISSUE THREAD

**Issue by roombobcat** [searxng/searx-instances#52]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Source code URL

No comment

### Comment

No comment

**Comment by tiekoetter** [comment]
Do you by any chance have an IP block list on your firewall? I can't access your instance via my home internet connection. I host a Tor relay on my IP, do you have a "Tor blocklist" active?

This is kind of not relevant and I could test your instance via a mobile internet connection but I wanted to ask if it was intended or not.

**Comment by roombobcat** [comment]
> Do you by any chance have an IP block list on your firewall? I can't access your instance via my home internet connection. I host a Tor relay on my IP, do you have a "Tor blocklist" active?
> 
> This is kind of not relevant and I could test your instance via a mobile internet connection but I wanted to ask if it was intended or not.

wasn't intended, didn't even realize the Tor block option was turned on in my UniFi Controller. should be accessible from Tor now.
