### ISSUE TITLE
Delete search.ldne.xyz

### ISSUE THREAD

**Issue by Nitrrine** [searxng/searx-instances#527]
Instance added by the issue #518

**Comment by unixfox** [comment]
Mmh instance added just one week ago. You should consider twice before requesting your instance to be added...

We expect instances added to the list to continue existing for a few years.

**Comment by Nitrrine** [comment]
Alright, yes that will be good for me. Yep I promise what it will be working for a year at least or even more, cause hosting SearXNG it's a joy!

**Comment by Nitrrine** [comment]
Hey @unixfox ! Everything should be good now, search.ldne.xyz is **up**!

**Comment by unixfox** [comment]
Ha that was quick. We can close this ticket then.
