### ISSUE TITLE
Add https://searx.orion-hub.fr

### ISSUE THREAD

**Issue by Nalem14** [searxng/searx-instances#53]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by tiekoetter** [comment]
Hi @Nalem14,

Your [TLS](https://cryptcheck.fr/https/searx.orion-hub.fr) and [CSP](https://observatory.mozilla.org/analyze/searx.orion-hub.fr) grade are not optimal.
Your instance can be added regardless; You will be ranked lower on searx.space.

Please confirm if you wish that your instance would be added anyways or change your TLS and CSP grade accordingly.

**Comment by tiekoetter** [comment]
Closing due to lack of replies.

**Comment by return42** [comment]
@Nalem14 please update your instance.
