### ISSUE TITLE
Add https://search.lollypopstealer.com

### ISSUE THREAD

**Issue by C-Keenan** [searxng/searx-instances#542]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

### Comment

If you have any questions/concerns/issues please contact dev@lollypopstealer.com and allow at least a 7 day grace period as I may not see the email right away. I should get back to you in a month at most probably much sooner. I'd love to help make the internet more private again and am hoping that this helps in doing so.

**Comment by ononoki1** [comment]
Please set `public_instance` to true.

> Yes I have configured the server.public_instance parameter.

Also, your site cannot get reached via HTTP. Please setup HTTP to HTTPS redirection.

**Comment by C-Keenan** [comment]
I may have misconfigured something in the instance as I have set the 'public_instance' parameter to true and it's running behind nginxpm so both should resolve to the https "version". I'll start sorting it out tomorrow as it's a bit late today.

**Comment by C-Keenan** [comment]
Issue with the 'public_instance' parameter should be fix now. Waiting for feedback on http only mode before I make any changes there.

**Comment by ononoki1** [comment]
> Edit : If http only access is required please do let me know and I can stop forcing https but would prefer to leave it if not required.

Your site now only supports HTTPS. Please also enable HTTP and redirect HTTP requests to HTTPS.

**Comment by C-Keenan** [comment]
I just typed 'http://search.lollypopstealer.com' into my address-bar and it automatically pushed me to https so I'm not seeing your error. Can you help me to recreate your steps to get the error?

**Comment by ononoki1** [comment]
> I just typed 'http://search.lollypopstealer.com/' into my address-bar and it automatically pushed me to https so I'm not seeing your error.

Your site enables HSTS, so after first access via HTTPS, your browser will only use HTTPS even if you explictly types HTTP.

To reproduce, please use curl: run `curl -v http://search.lollypopstealer.com`

**Comment by C-Keenan** [comment]
One moment while I do some troubleshooting. Can you provide the response I should be expecting when it goes right as I'd like to validate my results.

**Comment by ononoki1** [comment]
An example:
```
$ curl -I http://search.ononoki.org
HTTP/1.1 308 Permanent Redirect
Content-Type: text/html; charset=utf-8
Content-Length: 164
Connection: keep-alive
Location: https://search.ononoki.org/
```

**Comment by C-Keenan** [comment]
Ok, thank you. I'm currently blocked by the rate limit so I will have to wait a bit before I can continue testing, however, I will comment once I have good news.

**Comment by unixfox** [comment]
@C-Keenan Any news? Is your instance conformed?

**Comment by noosemanAL** [comment]
I tested this instance: https://search.lollypopstealer.com , Under "Engines" starting with "Files" through "Other", If you disable  "bt4g" or wikicommons.files or z-library or any default selection, It crashes and won't allow you to disable those.

![502](https://github.com/searxng/searx-instances/assets/52615094/0cf3b9c7-5e74-421c-b6bd-f6c1d4ac34e8)

**Comment by ononoki1** [comment]
Close due to lack of reply.

**Comment by C-Keenan** [comment]
Sorry for the unresponsiveness. @noosemanAL I just tested your "testing" comment and disabled all of what was mentioned in said comment and I am not getting the same results. It's possible that you were testing while server was rebooting as that is the page you should have seen my reverse proxy respond with at the time, currently the reverse proxy should no longer respond if endpoint can not be reached. In response to @unixfox , no, it has not yet been conformed as far as I'm aware due to the fact that we're supposed to receive a http-308 response and my server presents a 302 instead, likely due to my reverse proxy setup and I'm unsure how to move forward as the proxy project I use is not in my control and the issue we're seeing is above my head, I'm assuming the issue deals with replay attacks but I'm likely wrong. I have been busy with general life and other projects and this issue slipped my mind until I checked my github notifications today so I would, once again, like to apologize and promise to be more responsive in the future.

**Comment by C-Keenan** [comment]
![Screenshot (36)](https://github.com/user-attachments/assets/8f95dd6a-81d0-47a1-9bb8-7a6b0c99ea27)
![Screenshot (35)](https://github.com/user-attachments/assets/d107c198-69d8-43e5-8b3f-73ce4960e66e)
Uploading for proof of testing

**Comment by unixfox** [comment]
I'm sorry if you can't listen on HTTP only, it probably means that you lack of some server management knowledge to run a public instance. 

Running a public instance is difficult, it's not an easy task. You have to check the uptime of the server, deal against bots and more.

We thrive to get only experienced maintainers, as we want to have good instances on the list for a long time.

Try again in one year, during this time try to improve your Linux knowledge. By hosting more services, it's a good thing for learning how to maintain public services.

> as the proxy project I use is not in my control

If you want to get more experience, I would suggest you to stop using automated services that all the job for you and start configuring your reverse proxy manually in order to understand how things works.

**Comment by C-Keenan** [comment]
@unixfox ,

Nothing is automated, I use an Nginx Proxy Manager instance which is under my control but I don't have control over how it does things or the nginx knowledge to do it myself. I barely got [my website using nginx](https://github.com/C-Keenan/build), which can be reached [here](https://www.lollypopstealer.com), off the ground which is why I say I don't have the knowledge to do it myself. I'm still learning and, whether you or anyone else thinks so or not, that's ok for 2 reasons: 1. I'm putting in the effort to learn and 2. nginx, when you're learning on your own with barely any more guidance than YouTube videos, is hard especially when the documents provided, even by nginx themselves, are not exactly human readable without a dictionary sometimes. It'd be a different story too if caddy accepted the proxy connection but it gets mad because of "too many redirects" and I won't go through setting it directly up with ssl as it requires being reached directly from letsencrypt and nginx proxy manager already takes care of that.

You mention here

>  listen on HTTP only

I figured I'd let users that hit my instance know their connection is secure (encrypted I think is the better term), if there's an issue with that bring it up.

I came here and to your matrix chat server for help and despite the fact that 

> We thrive to get only experienced maintainers

you should be prepared for inexperienced people to pop in and need help understanding http status codes, and the best way to get them is by helping people learn.

The

> http-308

and

> 302

in my original comment, was talking about http status code responses.
You also mention

> deal against bots

and while I'm not entirely sure which file to link to, your own github documentation mentions fighting bots and how to manage it ***in your project***.

Yours truly,
C-Keenan

**Comment by unixfox** [comment]
I'm deeply sorry if my comments were a bit harsh.

I can see that you make good progress in your learning sessions. I truly think that you will more experienced in a few months.

Get back to us in half a year or one year with your progress and ask us to review again your instance. We will gladly do it.

**Comment by C-Keenan** [comment]
I too would like to apologize as my words were a bit more harsh than my actual meaning. I was admittedly upset, for reasons I'm willing to get into over private message if you're willing, I hope that despite my indignation my comment was able to get my point across. If I can explain the philosophy behind why I was a bit harsh, I subscribe to the phrase 

> "Be kind in your speech and ruthless in your execution." -me

where kindness does not always mean nice words and ruthlessness doesn't mean the same as like in the phrase "ruthless slaughter" but instead means to be sure to follow through with what you believe and say. However like I stated above if you'd like to hear why I was upset, admittedly for personal reasons, please reach out to me on the matrix server @shotgun_shogun or feel free to email me at dev@lollypopstealer.com and I will contact you with my personal email as well.
