### ISSUE TITLE
Add https://searx.rayk.xyz

### ISSUE THREAD

**Issue by mutix31** [searxng/searx-instances#55]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by tiekoetter** [comment]
Hi @mutix31,

Your [TLS](https://cryptcheck.fr/https/searx.rayk.xyz) and [CSP](https://observatory.mozilla.org/analyze/searx.rayk.xyz) grade are not optimal.
Your instance can be added regardless; You will be ranked lower on searx.space.

Filtron doesn't seem to work. `curl -i "https://searx.rayk.xyz/search?q=test"` returns `200` while it should return `429`.

I would also recommend that you should consider updating your instance to SearXNG.
You can consult this [guide](https://docs.searxng.org/admin/installation-switch2ng.html) or ask for help here.

Please confirm if you wish that your instance would be added anyways.
