### ISSUE TITLE
Add https://searx.mxchange.org

### ISSUE THREAD

**Issue by Quix0r** [searxng/searx-instances#567]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

### Comment

Local `/etc/searxng/limiter.toml` has `link_token=true` enabled.

**Comment by ononoki1** [comment]
Your [TLS](https://cryptcheck.fr/https/searx.mxchange.org) and [CSP](https://developer.mozilla.org/en-US/observatory/analyze?host=searx.mxchange.org) grades are not optimal. However, these grades can be ignored if you do not mind being ranked lower on searx.space. If you want to fix it before adding your instance, just do it and notify us when finished. Otherwise, tell us to add your instance now.

**Comment by Quix0r** [comment]
That's odd, it claims that headers for HSTS aren't set. But my configuration file contains them (by default I add them for all):
```
    <IfModule mod_headers.c>
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-XSS-Protection "1; mode=block"
        Header always set X-Frame-Options "sameorigin"
        Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
        Header always set Referrer-Policy: no-referrer
    </IfModule>
```

**Comment by Quix0r** [comment]
How I do it here:
```
    <Location />
        # httpd dmn entry PHP support BEGIN.
        # httpd dmn entry PHP support END.
        Options -Indexes +Includes +FollowSymLinks +MultiViews
        SetHandler uwsgi-handler
        uWSGISocket /run/uwsgi/app/searx/socket
        uWSGImaxVars 256
        <LimitExcept GET POST HEAD DELETE>
            <RequireAll>
                Require all granted
            </RequireAll>
        </LimitExcept>
    </Location>
```

**Comment by Quix0r** [comment]
My apache is not setting those headers you can see at https://developer.mozilla.org/en-US/observatory/analyze?host=searx.mxchange.org#headers

**Comment by Quix0r** [comment]
I finally made A+ !!! :1st_place_medal:

**Comment by Quix0r** [comment]
Pleasee add me now.

**Comment by Quix0r** [comment]
The `settings.yml` file does set the headers, I didn't know that.

**Comment by unixfox** [comment]
Please use the edit button. It's unnecessary to send that many comments.

**Comment by Quix0r** [comment]
Little head-up for my instance: The (by me) selected default search engines seem to block my server's IP address. So you have to choose your own instances and save the settings string in a text file.

**Comment by Quix0r** [comment]
I now run a small shell script:
```shell
#!/bin/sh

cd ${HOME}/searx/ || exit 255
git pull --all || exit 255
./manage py.build
```
Of course I need to execute `/etc/init.d/uwsgi restart` as root. But else it is now updated automatically.

**Comment by Quix0r** [comment]
I'm updating the node manually as I have touched the `settings.yml` file and it might cause conflicts on rebase.

**Comment by Quix0r** [comment]
`valkey` wasn't installed. Under Devuan/Debian you need to install `valkey-server` which listens on the same port as REDIS does. So if you need to run both, change the port in `/etc/valkey/valkey.conf` to an other number.

**Comment by Quix0r** [comment]
A `git diff` brings no output here as I have committed my local changes to `settings.yml`. I run it directly from the source root directory.

**Comment by Quix0r** [comment]
```ini
[uwsgi]
# Who will run the code
uid = searx
gid = searx

# Cache
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1

# disable logging for privacy
disable-logging = true

# Number of workers (usually CPU count)
workers = 2

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpreter config
single-interpreter = true
master = true
plugin = python3,http
lazy-apps = true
enable-threads = true

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /home/searx/searx/local/py3/
pythonpath = /home/searx/searx/
chdir = /home/searx/searx/searx/
```

**Comment by Quix0r** [comment]
That is might be my local commit on `settings.yml` then where I added my secret key, base URL and changed some other configuration. An idea is a to add `searx/settinhs.yml` to `.gitignore` and rename it `settings.yml.dist`. Then people can have local changes to their settings file and still have a clean checkout.

**Comment by Quix0r** [comment]
An other also very common way is to have 2 configuration files, a committed `settings.yml` and an ignored `settings-local.yml` with loading order settings -> local. So the local settings can overwrite "generic" settings.

**Comment by Quix0r** [comment]
I'm currently doing this here:
```crontab
$ crontab -l
MAILTO=webmaster@mxchange.org

# m h  dom mon dow   command
@weekly         ${HOME}/update.sh 2>&1
$ cat update.sh 
#!/bin/sh

cd ${HOME}/searx/ || exit 255
echo "$0: git pull ..."
git pull --all || exit 255
echo "$0: ./manage py.build ..."
./manage py.build || exit 255
echo "$0: All done."
$
```

**Comment by Quix0r** [comment]
And I can access it? https://searx.mxchange.org can be reached?

**Comment by vojkovic** [comment]
Do you have any bot detection or similar that could be causing this then?

If not, it could be a false alarm and I will need to check on the bot.

**Comment by vojkovic** [comment]
Will put it down to an issue with the bot then, I have manually closed the issue. Sorry for disturbing you!

**Comment by vojkovic** [comment]
Hi @Quix0r, can you please take a look at your auto update, your instance is running a version from February! `2026.2.5+f8a407c83`

**Comment by Quix0r** [comment]
`Powered by SearXNG - 2026.6.12+5ff8e633b ` is now fully updated. I have two separate steps to do:

1. Logged-in as user `searx`, run ./update.sh
2. Logged-in as `root`, restart the uwsgi service

It seems like that uwsgi doesn't notice the updated software when I just run the first step (already done by cron-job). I currently cannot find the option for the ini file where uwsgi scans for updated files and reloads automatically.

**Comment by Quix0r** [comment]
Or can I `screen -dmS searx ./manage webapp.run` and before update kill by sending a proper signal to it? Then I don't need root and uwsgi anymore.

**Comment by vojkovic** [comment]
Depending on your flavour of linux and how you first installed searxng, you might be able to just do `systemctl restart uwsgi@searxng` after updating. [Docs](https://docs.searxng.org/admin/installation-uwsgi.html#searxng-uwsgi)

**Comment by Quix0r** [comment]
No, that attempt wasn't working very well. Sending a QUIT to the main `searxng` process causes the worker processes to remain started. Hmm, I so far then remain with restarting manually uwsgi once I get the mail from the cronjob.

**Comment by vojkovic** [comment]
Hmmm interesting maybe @return42 could offer some help?

**Comment by vojkovic** [comment]
When saving preferences on your instance, the page redirects to https://searx.mxchange.orghttps//searx.mxchange.org/

Your reverse proxy is likely the cause, it is probably sending bad Host headers to the searxng process. This also impacts other areas such as the [opensearch.xml ](https://searx.mxchange.org/opensearch.xml)

Also, your instance is out of date again. Please can you update? If it happens again I will unfortunately need to remove your instance as I feel I am reminding you constantly every few months:

> I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.

**Comment by Quix0r** [comment]
Well, here the opensearch.xml is loading:
```xml
<OpenSearchDescription>
<ShortName>SearXNG</ShortName>
<LongName>SearXNG metasearch</LongName>
<Description>
SearXNG is a metasearch engine that respects your privacy.
</Description>
<InputEncoding>UTF-8</InputEncoding>
<Image type="image/png">
https://searx.mxchange.org/static/themes/simple/img/favicon.png
</Image>
<Url rel="results" type="text/html" method="POST" template="https://searx.mxchange.orghttps://searx.mxchange.org/search">
<Param name="q" value="{searchTerms}"/>
</Url>
<Url rel="self" type="application/opensearchdescription+xml" method="POST" template="https://searx.mxchange.orghttps://searx.mxchange.org/opensearch.xml"/>
<Query role="example" searchTerms="SearXNG"/>
<moz:SearchForm>
https://searx.mxchange.orghttps://searx.mxchange.org/search
</moz:SearchForm>
</OpenSearchDescription>
```

EDIT: Ah, I see the wrong URL `https://searx.mxchange.orghttps://searx.mxchange.org/search`. No idea why it does it.

**Comment by vojkovic** [comment]
It is due to the host header likely...

> Your reverse proxy is likely the cause, it is probably sending bad Host headers to the searxng process.

**Comment by Quix0r** [comment]
This is what I'm doing here:
```
    <Location />
        Options -Indexes +Includes +FollowSymLinks +MultiViews
        Require all granted

        # add the trailing slash
        RedirectMatch  308 https://searx.mxchange.org\$ https://searx.mxchange.org/
    
        ProxyPreserveHost On
        ProxyPass unix:/run/uwsgi/app/searxng/socket|uwsgi://uwsgi-uds-searxng/

        # see flaskfix.py
        RequestHeader set X-Scheme %{REQUEST_SCHEME}s
        RequestHeader set X-Script-Name https://searx.mxchange.org/
    
        # see limiter.py
        RequestHeader set X-Real-IP %{REMOTE_ADDR}s
        RequestHeader append X-Forwarded-For %{REMOTE_ADDR}s
    </Location>
```

**Comment by vojkovic** [comment]
Ah - probably is `RequestHeader set X-Script-Name https://searx.mxchange.org/`

**Comment by Quix0r** [comment]
Oh, that's the line I had to comment out and the `opensearch.xml` is working again. I misinterpreted this one:
```python
    '''Wrap the application in this middleware and configure the
    front-end server to add these headers, to let you quietly bind
    this to a URL other than / and to an HTTP scheme that is
    different than what is used locally.

    http://flask.pocoo.org/snippets/35/

    In nginx:
    location /myprefix {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /myprefix;
        }

    :param wsgi_app: the WSGI application
    '''
```

**Comment by vojkovic** [comment]
@Quix0r Your instance seems to be broken - some assets are returning 404 errors.

**Comment by Quix0r** [comment]
Hmm, I'm thinking of getting rid of uwsgi to free up some RAM for MariaDB. Unfortunately `./manage webapp.run` is for development and not "productive" installations. Or is there any slowness when I run it in a screen, e.g. `screen -dmS searxng ./manage webapp.run` ? Then I can just setup a reverse proxy on its port.
