### ISSUE TITLE
Add https://search.canine.tools

### ISSUE THREAD

**Issue by hyperdefined** [searxng/searx-instances#584]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

**Comment by ononoki1** [comment]
Hi @hyperdefined, the image search does not work well. Please either enable `image_proxy` or adjust your CSP policy.

**Comment by hyperdefined** [comment]
I'm not really sure why the images are failing, I have `image_proxy` enabled. I am using NGINX in place of Caddy:
```
location ~ ^/(config|healthz|stats/errors|stats/checker)$ {
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        proxy_pass http://localhost:3011;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
	
location ~* ^/static/ {
        add_header Cache-Control "public, max-age=31536000";
	proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:3011;
    }
	
location = /image_proxy {
        add_header Content-Security-Policy "default-src 'none'; img-src 'self' data:";
	proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:3011;
    }
	
location / {
        add_header Cache-Control "no-cache, no-store";
        add_header Pragma "no-cache";
        add_header Content-Security-Policy "upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/searxng/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com";
        proxy_pass http://localhost:3011;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

**Comment by hyperdefined** [comment]
I believed I have fixed it, please let me know if everything seems to be working and configured correctly.

**Comment by edevosc2c** [comment]
Hello,

Please whitelist anubis for check.searx.space. Otherwise your instance appears down on https://searx.space/#

**Comment by unixfox** [comment]
Hello,

Please whitelist anubis for check.searx.space. Otherwise your instance appears down on https://searx.space/#

**Comment by hyperdefined** [comment]
Is there a list of IPs I can whitelist?

**Comment by unixfox** [comment]
Yes the IPs that you get when you resolve check.searx.space, either in ipv4 or ipv6, depending on which ip network you are exposing your service.

**Comment by hyperdefined** [comment]
Awesome! Will do that. I thought I whitelisted it, but I was mistaken. Will do in a few hours.
