### ISSUE TITLE
Add https://searx.mbuf.net

### ISSUE THREAD

**Issue by hb9ery** [searxng/searx-instances#605]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I'll keep my instance up to date, at the very least 1 week old. Example program for keeping up to date: watchtower, cron, ouroboros.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection requirement

- [X] Yes I have configured the `server.public_instance` parameter.

**Comment by hb9ery** [comment]
Hi,
thanks for your feedback.

I had to figure out that valkey in settings.yml seems not yet working
fine. (runs on archlinux, replaced redis by valkey).

valkey+valkey socket url didn't make it

I had to declare redis and went fine.

Regards.


On Fri, Jun 27, 2025 at 11:21:59PM -0700, Brock Vojkovic typed:
:::: vojkovic left a comment (searxng/searx-instances#605)
:::: 
:::: Hi @hb9ery, could you please enable the `public_instance` parameter? Looks like your instance has not been marked as public. Let me know if you need help with this!
:::: 
:::: > Yes I have configured the `server.public_instance` parameter.
:::: 
:::: -- 
:::: Reply to this email directly or view it on GitHub:
:::: https://github.com/searxng/searx-instances/issues/605#issuecomment-3015016119
:::: You are receiving this because you were mentioned.
:::: 
:::: Message ID: ***@***.***>

-- 
| julien MABILLARD
|
| Web https://mbuf.net/about
| Gemini gemini://minitel.mbuf.net
| IPFS /ipns/k51qzi5uqu5dk9m0gsuh15fxhd5qp242um59kwhub9ffmnvjjpc1nlkmcwci54/about/

**Comment by vojkovic** [comment]
Looks good- cheers!

**Comment by hb9ery** [comment]
path to static was missing in uwsgi profile :)

kind regards

On Sat, Jun 28, 2025 at 07:12:08AM -0700, Brock Vojkovic typed:
:::: vojkovic left a comment (searxng/searx-instances#605)
:::: 
:::: @hb9ery Looks like your version tag is broken now - reporting in as 1.0.0
:::: 
:::: ![Image](https://github.com/user-attachments/assets/da58b750-8bfd-46c6-8ae6-9353ccaa5ad2)
:::: 
:::: -- 
:::: Reply to this email directly or view it on GitHub:
:::: https://github.com/searxng/searx-instances/issues/605#issuecomment-3015311393
:::: You are receiving this because you were mentioned.
:::: 
:::: Message ID: ***@***.***>

-- 
| julien MABILLARD
|
| Web https://mbuf.net/about
| Gemini gemini://minitel.mbuf.net
| IPFS /ipns/k51qzi5uqu5dk9m0gsuh15fxhd5qp242um59kwhub9ffmnvjjpc1nlkmcwci54/about/
