### ISSUE TITLE
Add https://searx.ppeb.me/

### ISSUE THREAD

**Issue by pollen00** [searxng/searx-instances#62]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

**Comment by unixfox** [comment]
I recommend serving searx from the main root (`/`) and not from a subpath (`/searx`) as it is better for the user experience.

**Comment by pollen00** [comment]
If sub domains are acceptable, then I can change it in about 10 hours when I get home to the root of a sub domain.

**Comment by tiekoetter** [comment]
@pollen00 Yes subdomains are acceptable.

**Comment by pollen00** [comment]
I've updated it to searx.ppeb.me.

**Comment by tiekoetter** [comment]
@pollen00 You are still serving SearXNG on the `/searx` path.

You can remove `proxy_set_header X-Script-Name /searx;` from your nginx config.

**Comment by pollen00** [comment]
Whoops, missed that. Should be fixed now.

**Comment by tiekoetter** [comment]
@pollen00 Your instance doesn't have a good [TLS](https://cryptcheck.fr/https/searx.ppeb.me) or [CSP](https://observatory.mozilla.org/analyze/searx.ppeb.me) grade.

You can still be added regardless (your instance will be ranked lower on searx.space); Please confirm if you want to be added regardless or change the grades accordingly.

**Comment by pollen00** [comment]
I've gotten my csp grade up to A+ but I just can't seem to improve my tls grade. I used the config listed in the new issue, the mozilla config, but it seems not to be helping.

```
server {
        listen 443 ssl http2;
        server_name searx.ppeb.me;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header Content-Security-Policy "default-src 'none'; script-src 'self'; style-src 'self'; img-src '* https: data:'; object-src 'none'; frame-ancestors 'none';" always;
        add_header X-Frame-Options "SAMEORIGIN" always;

        ssl_certificate /etc/letsencrypt/live/searx.ppeb.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/searx.ppeb.me/privkey.pem;

        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;

        ssl_dhparam /etc/nginx/dhparam;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        ssl_stapling on;
        ssl_stapling_verify on;

        ssl_trusted_certificate /etc/letsencrypt/live/searx.ppeb.me/fullchain.pem;

        resolver 192.168.1.1;

        location / {
             proxy_pass         http://localhost:4004/;
 
             proxy_set_header   Host             $host;
             proxy_set_header   Connection       $http_connection;
             proxy_set_header   X-Real-IP        $remote_addr;
             proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
             proxy_set_header   X-Scheme         $scheme;
         }
 
         location /searx/static/ {
             alias /usr/local/searx/searx-src/searx/static/;
         }
    }
```
This is my current config. I can't see anything wrong with it, so any directions on how to improve the tls grade would be appreciated.

**Comment by tiekoetter** [comment]
You need custom ciphers. `ssl_prefer_server_ciphers` needs to be `on`.

If you need a cipher list I can send you mine.

**Comment by pollen00** [comment]
Whoops, I hadn't copied that line from mozilla. It's E now, so I'm guessing I need a better cipher list now. Can you post yours?

**Comment by tiekoetter** [comment]
`ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA512:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA512:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;`

**Comment by pollen00** [comment]
Alright, everything is A+ now.

**Comment by tiekoetter** [comment]
Note that your current CSP header prevents some things (e.g. embedded videos) from loading. I will add your instance now. If you need help addressing these things feel free to ask.

**Comment by ononoki1** [comment]
@tiekoetter As far as I know, there is no `ECDHE-ECDSA-AES256-GCM-SHA512` or `ECDHE-RSA-AES256-GCM-SHA512` cipher.

**Comment by tiekoetter** [comment]
@ononoki1 It does exist but is not used. So you are right; thanks for pointing this out!

**Comment by ppebb** [comment]
Hi. I believe my instance was removed ages ago (at least over a year ago), likely due to uptime issues. Since then, I have switched ISPs and my uptime has been stable since. I believe my CSP and TLS grades are still good (I rechecked with mozilla observatory for CSP and am good there, but cryptcheck for TLS seems to error out). Is there the possibility of re-adding my instance?
