### ISSUE TITLE
Add https://searx.sev.monster

### ISSUE THREAD

**Issue by sevmonster** [searxng/searx-instances#63]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

No logging, secure TLS/headers.
![image](https://user-images.githubusercontent.com/16788697/168421098-08814e11-d2ac-4216-b56c-6baefcb8cbf9.png)
![image](https://user-images.githubusercontent.com/16788697/168421133-734b8032-0743-48d4-a32c-71f18d28a94a.png)

**Comment by tiekoetter** [comment]
Hi @sevmonster,

The limiter plugin doesn't seem to be enabled on your instance.
Running `curl -i "https://searx.sev.monster/search?q=test"` returns `200` instead of `429`.

**Comment by sevmonster** [comment]
`use_default_settings` and `server.limiter` are both `true`, so it should be...

**Comment by return42** [comment]
FYI: this instances loads images from a CDN .. by this, every request to this SearXNG instance  is tracked by unsplash.com

![grafik](https://user-images.githubusercontent.com/554536/231517913-14b34a8a-2e8c-43b3-9529-3324630b518a.png)

https://searx.sev.monster includes this CSS file https://sev.monster/css/vars.css where the image is loaded into the background

Related: https://github.com/searxng/searxng/issues/2335#issuecomment-1504671011

**Comment by unixfox** [comment]
> FYI: this instances loads images from a CDN .. by this, every request to this SearXNG instance is tracked by unsplash.com
> 
> ![grafik](https://user-images.githubusercontent.com/554536/231517913-14b34a8a-2e8c-43b3-9529-3324630b518a.png)
> 
> [searx.sev.monster](https://searx.sev.monster) includes this CSS file [sev.monster/css/vars.css](https://sev.monster/css/vars.css) where the image is loaded into the background
> 
> Related: [searxng/searxng#2335 (comment)](https://github.com/searxng/searxng/issues/2335#issuecomment-1504671011)

Well the requests for the main website are not going directly through a CDN server, so he is not breaking the rules here. But now on searx.space the instance is ranked lower and has an E letter:
![image](https://user-images.githubusercontent.com/4016501/231529178-82667214-53e2-4e54-9101-eddb04751a24.png)

**Comment by sevmonster** [comment]
> And I don't consider unsplash.com as a tracking software as the owner can't track through this service.

That's correct, I do not have access to any telemetry or other data from Unsplash, other than a total count of views of images—and this does not track per image requested from the API, but all images over the entire app. Additionally, the user does not make any API requests directly, it is all handled on the backend. The image link being requested by the user from my CSS is provided by the API and saved to the CSS file directly. This also means the link does not contain any per-user tracking data, only a secret provided by the API (the `ixid` parameter if I had to guess) which only links the image request to my registered API app and I assume the initial API call.

Due to the `Referer-Policy: strict-origin, no-referrer` header, and searches being made with `POST` data and not querystring, no search information should ever be transferred to Unsplash for compliant browsers; neither is any search data logged by my server either.

Pursuant to [section 6. Photo Interaction Data of the Unsplash API Terms)[https://unsplash.com/api-terms], Unsplash _does_ keep track of views of images, but does not store any other data besides IP address and some anonymized data for aggregation purposes:

> Unsplash may track user views, downloads, searches and likes of Photos within your Developer Apps via the image URLs or other technological means agreed between you and Unsplash to ensure the quality of and improve Unsplash products and services; perform research; and ensure compliance with these API Terms and applicable laws (“Photo Interaction Data”). Any tracking activity undertaken is via a random identifier that allows Unsplash to understand the approximate number of devices that produces the Photo Interaction Data. Unsplash does not link this identifier with any personal information other than Client IP address and Photo Interaction Data does not identify the user. Unsplash owns all Photo Interaction Data collected from use of your Developer Apps.

As I do not use the API for any purpose other than retrieving image links, and do not make any API calls from user-initiated actions, those parts of the Terms can be disregarded for this situation.

I would not include the Unsplash image if I did not personally feel that it did not encroach unnecessarily on user privacy, as the whole reason I use Searx/NG at all is because I value my own and others' privacy, as well as the anonymization of my and others' searches.

I appreciate the investigation into this matter, it's nice knowing that there are people ensuring the privacy of Searx users.

**Comment by return42** [comment]
> I would not include the Unsplash image if I did not personally feel that it did not encroach unnecessarily on user privacy, as the whole reason I use Searx/NG at all is because I value my own and others' privacy, as well as the anonymization of my and others' searches.

> Unsplash does keep track of views of images, but does not store any other data besides IP address and some anonymized data for aggregation purposes

Why not placing the image on your server?

**Comment by sevmonster** [comment]
> Why not placing the image on your server?

I would love to, but it is unfortunately against Unsplash API Terms. See again [section 6](https://unsplash.com/api-terms):

> 6. Photo Interaction Data
> In connection with any Photos that you access via the APIs, you must directly use or embed the related image URLs returned by the API in your Developer Apps (generally referred to as “hotlinking”) in accordance with the API Guidelines.

This only covers the API and not `source.unsplash.com`, but who knows when they will turn that service off.

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by sevmonster** [comment]
I am doing no such thing.

**Comment by unixfox** [comment]
I don't know, something is blocking github actions.

Otherwise no error would be reported.

As you can see it works on all the instances expect yours: https://github.com/searxng/searx-instances-uptime

**Comment by sevmonster** [comment]
It says it's up now? I haven't made any changes.

**Comment by unixfox** [comment]
Mmmh ok. I'm going to close the issue manually. Hoping that was just a bug.
