### ISSUE TITLE
Add https://serx.ml

### ISSUE THREAD

**Issue by ice9smart** [searxng/searx-instances#64]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

### Source code URL

https://github.com/searxng/searxng

**Comment by tiekoetter** [comment]
@return42 I would count that as analytics.

**Comment by unixfox** [comment]
> @return42 I would count that as analytics.

It's not displayed unless the user do too many requests, I wouldn't count that as analytics as the google recaptcha is not loaded on every page.
I just created a PR for adding a comment about that: https://github.com/searxng/searx-instances/pull/69
