### ISSUE TITLE
Add https:/search.ohaa.xyz

### ISSUE THREAD

**Issue by OhaDerErste** [searxng/searx-instances#65]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by tiekoetter** [comment]
Hi @OhaDerErste,
the morty proxy isn't working on your instance. Please fix this or switch to the internal image proxy.
