### ISSUE TITLE
Edit https://searx.mha.fi

### ISSUE THREAD

**Issue by datanomi** [searxng/searx-instances#66]
Instance added by the issue (https://github.com/searx/searx-instances/issues/158)
Add Hidden Service link to my instance (http://searx.micohauwkjbyw5meacrb4ipicwvwg4xtzl7y7viv53kig2mdcsvwkyyd.onion/)
It's also advertised in the Onion-Location header

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#searxng:matrix.org
then pinging @\unixfox, @\dalf and @\mrpaulblack for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices (like how to protect against bots), announcing big changes in searxng and more.

**Comment by unixfox** [comment]
A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st December 2023. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.

**Comment by unixfox** [comment]
Removed your onion url because it doesn't work anymore: http://searx.micohauwkjbyw5meacrb4ipicwvwg4xtzl7y7viv53kig2mdcsvwkyyd.onion/

**Comment by unixfox** [comment]
@ntrezowan Important step above https://github.com/searxng/searx-instances/issues/66#issuecomment-1753688133! The deadline has already passed, if you do not conform we will have to remove your instance by the end of the year.

**Comment by unixfox** [comment]
hello,
your instance was removed for being down for too much time: https://github.com/searxng/searx-instances/commit/3e58656085460cc63524cf76dced47b9e8ce47d6
10 days, 4 hours, 40 minutes: https://github.com/searxng/searx-instances-uptime/issues/3726

You have not notified us as per our new rules: https://github.com/searxng/searx-instances/blob/master/.github/ISSUE_TEMPLATE/add-instance.yaml

If you want to add back your instance, you will need to recreate a new issue here: https://github.com/searxng/searx-instances/issues/new/choose
