### ISSUE TITLE
Add https://asowneryt.cloudns.nz

### ISSUE THREAD

**Issue by ASOwnerYT** [searxng/searx-instances#71]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

Looks like this is the first instance in the Oceania (Australia/NZ) region as far as I can see :)

Uses [searxng-docker](https://github.com/searxng/searxng-docker) on default settings

**Comment by unixfox** [comment]
Removing instance due to bad uptime: https://github.com/searxng/searx-instances-uptime/blob/a916f369b8e365d8b970f2b944832fd0ee67bfb9/api/asowneryt-cloudns-nz/uptime-month.json

Required uptime of 90% per month
