### ISSUE TITLE
Add https://search.chemicals-in-the-water.eu

### ISSUE THREAD

**Issue by somerandomusername666** [searxng/searx-instances#72]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by tiekoetter** [comment]
@somerandomusername666 Your are serving SearXNG from the `/searx` path. Is this intended?

**Comment by somerandomusername666** [comment]
@tiekoetter hello, i don't think it was intentional to let the search go to the /searx path im aware of this behaviour and im trying to just let it run from the main domain path (i dont know if i explain things correctly)

**Comment by somerandomusername666** [comment]
Update: it appears i have broken something, i'd have to reinstall it

**Comment by tiekoetter** [comment]
@somerandomusername666 do you need any help?

**Comment by somerandomusername666** [comment]
@tiekoetter thanks for the offer but i got it working now using docker (i noticed this pretty late)

**Comment by unixfox** [comment]
I can't reach your server in IPv6:
$ curl -6 -m 10 -I https://search.chemicals-in-the-water.eu
curl: (28) Failed to connect to search.chemicals-in-the-water.eu port 443 after 5010 ms: Operation timed out

**Comment by somerandomusername666** [comment]
Hello, yes that is indeed the case. I'm trying to make it work with docker
but docker doesn't want to use IPv6.

**Comment by unixfox** [comment]
Then please remove the IPv6 address on your domain until it's fixed.

Have a look at docs too: https://docs.docker.com/config/daemon/ipv6/

**Comment by somerandomusername666** [comment]
Okay, I had removed it yesterday as it wasn't working. But I managed to
make it work (I hope). Does it automatically get updated on the instances
site or how does it work?

**Comment by unixfox** [comment]
Yes you will have to wait for next time searx.space do a scan of your instance and in the column IPv6 you should have a "YES"
