### ISSUE TITLE
Add https://searxng.au/searx

### ISSUE THREAD

**Issue by wale** [searxng/searx-instances#78]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/searxng/searxng

**Comment by wale** [comment]
Yeah, I tried using the intermediate config from the Mozilla SSL generator, not fun.
> Your instance also seems to serve SearXNG from the /searx path (Is this intended?)
Yes and no, the /searx path only comes up when you *search*. https://searxng.au will still resolve without the /searx path. This wasn't intended, but it's much better since your search terms won't come up in the history (neither in the URL, or the page title)

**Comment by unixfox** [comment]
> Yes and no, the /searx path only comes up when you _search_. [searxng.au](https://searxng.au) will still resolve without the /searx path. This wasn't intended, but it's much better since your search terms won't come up in the history (neither in the URL, or the page title)

That won't appear too if you remove this path though. You would just have /search as a path when doing a search.

**Comment by tiekoetter** [comment]
@wale Any update?

**Comment by wale** [comment]
Do you mind adding the instance without the fixes? The CSP/TLS configuration will be at a detriment but that will be changed later.
