### ISSUE TITLE
Add https://search.modalogi.com/searx

### ISSUE THREAD

**Issue by georg-mayer** [searxng/searx-instances#8]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by unixfox** [comment]
Hello,
The preferences page is broken, when saving it doesn't work.

Apart from that everything is fine.

**Comment by unixfox** [comment]
Hello,
Could you serve searx from the root domain (/) instead of /searx?

**Comment by unixfox** [comment]
Closing due to the lack of replies. Please reopen if you still want to add your instance.
