### ISSUE TITLE
Add https://searx.vern.cc

### ISSUE THREAD

**Issue by gi-yt** [searxng/searx-instances#80]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

Hidden service is located @ searx.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion

**Comment by tiekoetter** [comment]
Hi @gi-yt 
Your [TLS](https://cryptcheck.fr/https/searx.vern.cc) and [CSP](https://observatory.mozilla.org/analyze/searx.vern.cc) config is not optimal. Your instance also has some duplicate headers.
Your instance can still be added anyways it will just be ranked lower on searx.space.

**Comment by tiekoetter** [comment]
@gi-yt Any update?

**Comment by gi-yt** [comment]
no i have sadly been busy with other stuff. i will update you once its done

**Comment by gi-yt** [comment]
we have had a lot of issues with being completely ratelimited in a lot of places, so i dont think its a good idea to add the instance. (google, ddg have been fully ratelimited for a while, doesnt even work on our whoogle instance)
