### ISSUE TITLE
Add https://searx.becomesovran.com

### ISSUE THREAD

**Issue by Enkimin** [searxng/searx-instances#81]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by tiekoetter** [comment]
Hi @Enkimin 
Your Server seems to have some IPv6 problems (Check https://www.ssllabs.com/ssltest/analyze.html?d=searx.becomesovran.com&s=2a03%3ab0c0%3a3%3ad0%3a0%3a0%3a1095%3aa001&hideResults=on&ignoreMismatch=on). Please fix this.

I would also recommend that you should consider switching your instance to SearXNG.
You can consult this [guide](https://docs.searxng.org/admin/installation-switch2ng.html) or ask for help here.
Your instance can be added anyways.

**Comment by Enkimin** [comment]
Derp I swapped server regions recently and forgot to change the AAAA record the new IP. Changed the record and re-ran my atuo SSL. its fixed now thanks for that. 

Not opposed to swithcing but whats the advantage to swapping to SearXNG? 

On Friday, June 10, 2022 12:06 PDT, Léon Tiekötter ***@***.***> wrote:
 
 
Hi @Enkimin
Your Server seems to have some IPv6 problems (Check https://www.ssllabs.com/ssltest/analyze.html?d=searx.becomesovran.com&s=2a03%3ab0c0%3a3%3ad0%3a0%3a0%3a1095%3aa001&hideResults=on&ignoreMismatch=on). Please fix this.
I would also recommend that you should consider switching your instance to SearXNG.
You can consult this guide or ask for help here.
Your instance can be added anyways.

**Comment by tiekoetter** [comment]
SearXNG has many things which differentiate it from SearX (A breakdown can be found in the [README](https://github.com/searxng/searxng/blob/master/README.rst))

Some important points:

- User experience
- Setup (e.g. docker image)
- Contributing

**Comment by Enkimin** [comment]
ok I swapped over to NG. I do like it better. I should be good to go unless you see any detramental issues.



On Friday, June 10, 2022 13:39 PDT, Léon Tiekötter ***@***.***> wrote:
 
 
SearXNG has many things which differentiate it from SearX (A breakdown can be found in the README)
Some important points:
 * User experience * Setup (e.g. docker image) * Contributing
