### ISSUE TITLE
Add https://search.sapti.me

### ISSUE THREAD

**Issue by theanonymousexyz** [searxng/searx-instances#82]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/searxng/searxng

#### Alternative URLs

Onion service: `http://gbat2pbpg7ys3fi3pbp64667tt5x66mg45xok35bxdw7v55brm7a27yd.onion`

**Comment by vojkovic** [comment]
@samsapti Your instance has been returning 5xx errors for around a month https://github.com/searxng/searx-instances-uptime/issues/12705
