### ISSUE TITLE
Add https://searxng.tordenskjold.de

### ISSUE THREAD

**Issue by CaptainTordenskjold** [searxng/searx-instances#86]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

I just added the possibility to link my main page where I explain why I provide a public instance (among other things, work in progress) (I got the idea from https://searx.tiekoetter.com/). So I still link to the original searxng github page to examine the source code. If this is not desired, please let me know so I can adjust it.

**Comment by unixfox** [comment]
@CaptainTordenskjold 

A new big change has been introduced 🎉!

Please read this documentation for how to proceed: https://gist.github.com/unixfox/4e22730769540fe5b9f1943a86439761

We are going to make mandatory this new parameter by 1st January 2024. Any instance that do not have this parameter enabled won't be allowed in the public list anymore.

We can make exceptions in case you really do not want to enable our bot limiter solution, but you will have to send us proofs: clearly stating how you detect bots, how you actively deal with them and also prove that it really works.

Feel free to ask here if you have any troubles setting up this new parameter.
