### ISSUE TITLE
Add https://opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searx-instances#87]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Source code URL

https://github.com/paulgoio/searxng

### Comment

I'm using the Paulgoio fork. Thanks!

**Comment by tiekoetter** [comment]
Hi @extremelyonline,
Please fix your contact E-Mail.
Your [TLS](https://cryptcheck.fr/https/opnxng.com) and [CSP](https://observatory.mozilla.org/analyze/opnxng.com) grade are not optimal.
Your instance can be added regardless; You will be ranked lower on searx.space.

Please confirm if you wish that your instance would be added anyways or change your TLS and CSP grade accordingly.

**Comment by extremelyonline** [comment]
Thanks @tiekoetter. I have fixed the email and both the TLS and CSP.
(Please refresh cryptcheck  when you check. I tested using a subdomain.)

Would you please check and add my instance if they are optimal?
