### ISSUE TITLE
Add https://searx.zcyph.cc

### ISSUE THREAD

**Issue by zcyph** [searxng/searx-instances#98]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

Hidden service: http://4tz2vlnwk2apf2rpinkqv6uxvfgo5xjx6vl5vp7lxgaiooumetjpstqd.onion

**Comment by ononoki1** [comment]
Hi @zcyph
 
Your [TLS](https://cryptcheck.fr/https/searx.zcyph.cc) and [CSP](https://observatory.mozilla.org/analyze/searx.zcyph.cc) config is not optimal. It's recommended to optimize it to protect user's security.

Besides, your web server only supports HTTP/1.1. We recommend you to enable HTTP/2 support to improve performance. I noticed that you are using NGINX. You can simply [add `http2` parameter in `listen` directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen).

Your instance can still be added in searx.space even if you do not follow the advice above. It will just be ranked lower. Please confirm whether you wish that your instance would be added anyway or change your config accordingly.

**Comment by zcyph** [comment]
Hi,

I have made some adjustments, it should be looking better now for the CSP and HTTP2 stuff. For the TLS, I believe it's because certbot/LE goes with the intermediary configuration for better backwards compatibility, but still prioritizes the more modern ciphers for browsers that support it. I checked SSL Labs and see an A+ rating there, so I think it should be OK. Thanks!

**Comment by ononoki1** [comment]
There are still some issues.

- Your CSP policy is too strict. Image search may not work (e.g. https://searx.zcyph.cc/searx/search?q=test&category_images=on).
- You are serving SearXNG in both root and path `/searx` (https://searx.zcyph.cc and https://searx.zcyph.cc/searx/). Is that intended?
- Mozilla's intermediate config is not secure enough. You only need to disable DH cihpers (which are `DHE-RSA-AES128-GCM-SHA256` and `DHE-RSA-AES256-GCM-SHA384`) to get A+ in [cryptcheck.fr](https://cryptcheck.fr/https/searx.zcyph.cc). Would you like to do that?

**Comment by zcyph** [comment]
/searx path and TSL ciphers should be better now.

I'm not that familiar with CSP and am having difficulty getting that working properly in both Firefox and Chrome - would you happen to have a working example config I could check?

**Comment by ononoki1** [comment]
Maybe you can try this:

```txt
default-src 'self'; img-src * data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'
```

**Comment by zcyph** [comment]
Thanks, I've tried that but it still doesn't seem to work properly. The CSS seems to stop working in Firefox on the images tab, and Chrome doesn't load the images page at all with an `ERR_HTTP2_PROTOCOL_ERROR`.

This is the nginx conf:

```
server {
    server_name searx.zcyph.cc 4tz2vlnwk2apf2rpinkqv6uxvfgo5xjx6vl5vp7lxgaiooumetjpstqd.onion;
    location / {
        proxy_pass http://127.0.0.1:1234;
        proxy_headers_hash_max_size 512;
        proxy_headers_hash_bucket_size 128;
        proxy_set_header   Host             $host;
        proxy_set_header   Connection       $http_connection;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-Scheme         $scheme;
    }

    add_header Onion-Location http://4tz2vlnwk2apf2rpinkqv6uxvfgo5xjx6vl5vp7lxgaiooumetjpstqd.onion$request_uri;
    add_header Content-Security-Policy "default-src 'self'; img-src * data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'";
    add_header Strict-Transport-Security "max-age=31536000";
    add_header X-Frame-Options "SAMEORIGIN";

    listen 443 ssl http2;
    ssl_session_cache shared:MozSSL:10m;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/letsencrypt/live/searx.zcyph.cc/fullchain.pem;
    ssl_certificate /etc/letsencrypt/live/searx.zcyph.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/searx.zcyph.cc/privkey.pem;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA2>
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = searx.zcyph.cc) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name searx.zcyph.cc 4tz2vlnwk2apf2rpinkqv6uxvfgo5xjx6vl5vp7lxgaiooumetjpstqd.onion;
    return 404;
}
```
